/*****************************************************/
/**  Autogenerated Spam accent vectors for cmu_us_slt   */
/*****************************************************/
static const float cmu_us_slt_spamf0_accent_frame_0[] = { 
 0.148799, 0.073203, 0.152792, 0.092641, 0.160786, 0.100491, -0.486551, 0.645222, };
static const float cmu_us_slt_spamf0_accent_frame_1[] = { 
 0.111634, 0.054704, 0.111654, 0.059191, 0.137716, 0.082197, -0.345135, 0.705097, };
static const float cmu_us_slt_spamf0_accent_frame_2[] = { 
 0.159771, 0.056055, 0.171105, 0.074276, 0.173809, 0.100367, -0.447216, 0.636109, };
static const float cmu_us_slt_spamf0_accent_frame_3[] = { 
 0.168296, 0.071594, 0.189288, 0.100632, 0.193119, 0.096235, -0.429845, 0.555692, };
static const float cmu_us_slt_spamf0_accent_frame_4[] = { 
 0.175705, 0.074056, 0.210862, 0.114115, 0.205684, 0.110999, -0.527230, 0.424720, };
static const float cmu_us_slt_spamf0_accent_frame_5[] = { 
 0.180085, 0.070788, 0.208797, 0.100641, 0.217185, 0.122421, -0.579968, 0.413228, };
static const float cmu_us_slt_spamf0_accent_frame_6[] = { 
 0.175613, 0.067338, 0.209312, 0.104796, 0.220239, 0.125254, -0.470382, 0.483654, };
static const float cmu_us_slt_spamf0_accent_frame_7[] = { 
 0.210245, 0.060678, 0.245638, 0.087648, 0.230287, 0.132097, -0.496895, 0.474457, };
static const float cmu_us_slt_spamf0_accent_frame_8[] = { 
 0.199184, 0.057705, 0.251451, 0.100717, 0.255303, 0.132003, -0.465694, 0.408054, };
static const float cmu_us_slt_spamf0_accent_frame_9[] = { 
 0.219658, 0.056648, 0.282089, 0.097992, 0.268294, 0.133463, -0.498839, 0.324150, };
static const float cmu_us_slt_spamf0_accent_frame_10[] = { 
 0.117801, 0.061965, 0.110795, 0.065195, 0.143519, 0.098575, -0.773096, 0.434933, };
static const float cmu_us_slt_spamf0_accent_frame_11[] = { 
 0.128759, 0.073174, 0.120833, 0.076213, 0.142092, 0.095056, -0.637892, 0.638443, };
static const float cmu_us_slt_spamf0_accent_frame_12[] = { 
 0.145598, 0.077624, 0.157795, 0.093707, 0.186781, 0.098462, -0.332038, 0.647099, };
static const float cmu_us_slt_spamf0_accent_frame_13[] = { 
 0.124369, 0.065594, 0.117476, 0.066230, 0.155563, 0.075323, -0.020558, 0.790240, };
static const float cmu_us_slt_spamf0_accent_frame_14[] = { 
 0.126710, 0.067561, 0.128662, 0.077905, 0.171733, 0.102451, -0.392839, 0.693160, };
static const float cmu_us_slt_spamf0_accent_frame_15[] = { 
 0.103325, 0.057534, 0.097939, 0.056803, 0.125806, 0.068059, -0.570971, 0.630562, };
static const float cmu_us_slt_spamf0_accent_frame_16[] = { 
 0.082852, 0.052990, 0.078676, 0.059659, 0.123264, 0.070374, -0.504347, 0.688906, };
static const float cmu_us_slt_spamf0_accent_frame_17[] = { 
 0.097162, 0.060261, 0.096108, 0.066437, 0.137524, 0.078048, -0.481988, 0.673377, };
static const float cmu_us_slt_spamf0_accent_frame_18[] = { 
 0.089864, 0.056377, 0.085333, 0.064803, 0.145066, 0.085610, -0.237146, 0.805026, };
static const float cmu_us_slt_spamf0_accent_frame_19[] = { 
 0.136897, 0.075180, 0.141159, 0.085223, 0.145789, 0.080001, -0.639904, 0.490389, };
static const float cmu_us_slt_spamf0_accent_frame_20[] = { 
 0.137799, 0.064980, 0.146621, 0.080864, 0.177783, 0.103142, -0.460001, 0.606252, };
static const float cmu_us_slt_spamf0_accent_frame_21[] = { 
 0.109135, 0.060605, 0.106549, 0.066786, 0.146331, 0.077869, -0.438307, 0.699755, };
static const float cmu_us_slt_spamf0_accent_frame_22[] = { 
 0.123602, 0.077251, 0.136947, 0.091292, 0.183203, 0.090218, -0.171093, 0.630490, };
static const float cmu_us_slt_spamf0_accent_frame_23[] = { 
 0.116186, 0.066778, 0.128016, 0.080590, 0.177563, 0.084879, -0.338887, 0.583723, };
static const float cmu_us_slt_spamf0_accent_frame_24[] = { 
 0.107581, 0.064235, 0.108418, 0.075447, 0.148474, 0.092528, -0.451916, 0.693468, };
static const float cmu_us_slt_spamf0_accent_frame_25[] = { 
 0.116828, 0.069649, 0.121693, 0.078434, 0.158719, 0.084000, -0.523620, 0.546187, };
static const float cmu_us_slt_spamf0_accent_frame_26[] = { 
 0.090714, 0.052755, 0.094759, 0.063038, 0.161369, 0.079579, -0.283751, 0.658383, };
static const float cmu_us_slt_spamf0_accent_frame_27[] = { 
 0.159563, 0.072836, 0.175574, 0.088832, 0.180084, 0.081759, 0.140148, 0.622433, };
static const float cmu_us_slt_spamf0_accent_frame_28[] = { 
 0.183742, 0.079240, 0.186930, 0.085107, 0.184131, 0.086385, -0.077304, 0.732138, };
static const float cmu_us_slt_spamf0_accent_frame_29[] = { 
 0.179955, 0.075743, 0.176666, 0.078905, 0.168665, 0.079624, -0.096256, 0.801682, };
static const float cmu_us_slt_spamf0_accent_frame_30[] = { 
 0.192580, 0.072386, 0.196147, 0.077316, 0.167581, 0.099355, -0.442053, 0.679848, };
static const float cmu_us_slt_spamf0_accent_frame_31[] = { 
 0.181674, 0.077589, 0.181231, 0.081952, 0.170330, 0.095151, -0.319200, 0.725173, };
static const float cmu_us_slt_spamf0_accent_frame_32[] = { 
 0.204685, 0.079482, 0.210818, 0.087769, 0.184081, 0.088601, -0.244584, 0.723217, };
static const float cmu_us_slt_spamf0_accent_frame_33[] = { 
 0.124411, 0.062083, 0.123974, 0.070526, 0.146844, 0.079044, -0.357170, 0.710853, };
static const float cmu_us_slt_spamf0_accent_frame_34[] = { 
 0.137861, 0.075018, 0.148843, 0.092711, 0.176857, 0.085097, -0.214751, 0.688905, };
static const float cmu_us_slt_spamf0_accent_frame_35[] = { 
 0.135293, 0.068160, 0.145359, 0.088282, 0.174392, 0.077434, -0.009544, 0.705736, };
static const float cmu_us_slt_spamf0_accent_frame_36[] = { 
 0.111686, 0.058591, 0.116596, 0.072698, 0.156617, 0.075090, -0.173338, 0.722039, };
static const float cmu_us_slt_spamf0_accent_frame_37[] = { 
 0.155048, 0.070449, 0.177119, 0.092825, 0.192236, 0.091629, -0.299510, 0.606609, };
static const float cmu_us_slt_spamf0_accent_frame_38[] = { 
 0.093652, 0.058070, 0.094510, 0.068179, 0.140543, 0.077634, -0.170425, 0.758271, };
static const float cmu_us_slt_spamf0_accent_frame_39[] = { 
 0.114983, 0.060530, 0.121935, 0.080104, 0.156317, 0.083558, -0.017483, 0.729364, };
static const float cmu_us_slt_spamf0_accent_frame_40[] = { 
 0.115202, 0.064609, 0.119335, 0.078387, 0.161047, 0.090700, -0.300123, 0.716034, };
static const float cmu_us_slt_spamf0_accent_frame_41[] = { 
 0.123710, 0.063970, 0.127291, 0.072457, 0.164733, 0.085185, -0.098995, 0.713767, };
static const float cmu_us_slt_spamf0_accent_frame_42[] = { 
 0.108758, 0.068581, 0.104898, 0.071361, 0.158404, 0.095879, -0.338012, 0.733114, };
static const float cmu_us_slt_spamf0_accent_frame_43[] = { 
 0.136113, 0.069977, 0.153164, 0.088590, 0.186825, 0.100556, -0.339608, 0.611948, };
static const float cmu_us_slt_spamf0_accent_frame_44[] = { 
 0.130338, 0.073838, 0.140836, 0.088376, 0.178315, 0.067448, 0.115015, 0.613230, };
static const float cmu_us_slt_spamf0_accent_frame_45[] = { 
 0.145368, 0.062011, 0.168746, 0.085057, 0.188146, 0.095534, -0.314577, 0.561044, };
static const float cmu_us_slt_spamf0_accent_frame_46[] = { 
 0.133649, 0.066617, 0.152124, 0.086865, 0.186158, 0.082443, -0.086239, 0.629830, };
static const float cmu_us_slt_spamf0_accent_frame_47[] = { 
 0.132518, 0.072547, 0.145075, 0.089144, 0.182965, 0.093659, -0.417541, 0.584840, };
static const float cmu_us_slt_spamf0_accent_frame_48[] = { 
 0.131002, 0.069267, 0.141771, 0.087455, 0.194385, 0.105215, -0.235090, 0.698336, };
static const float cmu_us_slt_spamf0_accent_frame_49[] = { 
 0.147915, 0.066943, 0.167610, 0.092570, 0.207102, 0.095967, -0.082812, 0.657203, };
static const float cmu_us_slt_spamf0_accent_frame_50[] = { 
 0.103311, 0.050967, 0.105993, 0.061944, 0.137602, 0.070194, -0.293463, 0.691880, };
static const float cmu_us_slt_spamf0_accent_frame_51[] = { 
 0.119026, 0.059099, 0.126754, 0.070180, 0.150761, 0.064827, -0.112478, 0.684018, };
static const float cmu_us_slt_spamf0_accent_frame_52[] = { 
 0.140344, 0.068907, 0.143377, 0.078818, 0.165705, 0.062166, 0.332395, 0.566679, };
static const float cmu_us_slt_spamf0_accent_frame_53[] = { 
 0.116186, 0.064201, 0.114389, 0.070894, 0.158587, 0.080824, 0.076901, 0.758680, };
static const float cmu_us_slt_spamf0_accent_frame_54[] = { 
 0.140697, 0.065191, 0.145576, 0.082322, 0.173302, 0.069175, 0.283293, 0.617495, };
static const float cmu_us_slt_spamf0_accent_frame_55[] = { 
 0.133658, 0.065436, 0.144890, 0.082283, 0.171742, 0.067468, 0.068963, 0.640486, };
static const float cmu_us_slt_spamf0_accent_frame_56[] = { 
 0.127244, 0.063020, 0.146314, 0.082866, 0.179796, 0.087330, -0.228560, 0.576495, };
static const float cmu_us_slt_spamf0_accent_frame_57[] = { 
 0.127754, 0.059127, 0.156484, 0.080568, 0.199432, 0.080587, -0.150868, 0.476419, };
static const float cmu_us_slt_spamf0_accent_frame_58[] = { 
 0.115665, 0.060445, 0.134416, 0.088848, 0.175770, 0.086550, -0.336298, 0.597063, };
static const float cmu_us_slt_spamf0_accent_frame_59[] = { 
 0.136276, 0.063398, 0.147712, 0.081062, 0.169039, 0.081325, -0.081368, 0.695260, };
static const float cmu_us_slt_spamf0_accent_frame_60[] = { 
 0.137422, 0.067616, 0.153916, 0.092011, 0.178784, 0.093203, -0.243993, 0.662869, };
static const float cmu_us_slt_spamf0_accent_frame_61[] = { 
 0.131740, 0.065344, 0.154048, 0.090226, 0.179629, 0.078655, -0.086680, 0.626561, };
static const float cmu_us_slt_spamf0_accent_frame_62[] = { 
 0.141732, 0.065518, 0.164965, 0.090763, 0.189237, 0.070995, 0.048829, 0.579427, };
static const float cmu_us_slt_spamf0_accent_frame_63[] = { 
 0.154204, 0.066489, 0.173376, 0.085854, 0.187960, 0.085682, -0.281639, 0.629404, };
static const float cmu_us_slt_spamf0_accent_frame_64[] = { 
 0.158965, 0.071266, 0.173422, 0.088794, 0.194993, 0.079177, 0.002589, 0.680082, };
static const float cmu_us_slt_spamf0_accent_frame_65[] = { 
 0.151335, 0.061999, 0.169325, 0.090741, 0.188661, 0.091015, -0.214860, 0.644062, };
static const float cmu_us_slt_spamf0_accent_frame_66[] = { 
 0.196501, 0.075620, 0.189666, 0.081480, 0.192294, 0.075727, 0.087184, 0.772218, };
static const float cmu_us_slt_spamf0_accent_frame_67[] = { 
 0.204034, 0.077587, 0.200777, 0.080220, 0.200705, 0.094568, -0.000560, 0.775433, };
static const float cmu_us_slt_spamf0_accent_frame_68[] = { 
 0.151852, 0.063949, 0.162478, 0.082134, 0.193695, 0.077757, 0.165662, 0.664408, };
static const float cmu_us_slt_spamf0_accent_frame_69[] = { 
 0.168830, 0.067993, 0.183410, 0.087625, 0.203688, 0.097117, -0.053756, 0.684345, };
static const float cmu_us_slt_spamf0_accent_frame_70[] = { 
 0.142216, 0.070154, 0.155174, 0.094696, 0.187395, 0.083266, -0.041761, 0.680119, };
static const float cmu_us_slt_spamf0_accent_frame_71[] = { 
 0.166416, 0.064301, 0.185904, 0.089684, 0.196828, 0.095750, -0.152170, 0.666527, };
static const float cmu_us_slt_spamf0_accent_frame_72[] = { 
 0.159665, 0.059448, 0.203812, 0.091090, 0.204207, 0.087886, -0.232837, 0.450234, };
static const float cmu_us_slt_spamf0_accent_frame_73[] = { 
 0.135196, 0.070728, 0.170605, 0.102066, 0.219715, 0.095895, -0.326237, 0.449132, };
static const float cmu_us_slt_spamf0_accent_frame_74[] = { 
 0.139241, 0.061369, 0.158997, 0.082854, 0.194281, 0.094627, -0.245568, 0.604484, };
static const float cmu_us_slt_spamf0_accent_frame_75[] = { 
 0.159807, 0.063272, 0.200590, 0.091158, 0.212727, 0.093426, -0.148443, 0.518080, };
static const float cmu_us_slt_spamf0_accent_frame_76[] = { 
 0.139980, 0.063206, 0.154255, 0.083791, 0.192108, 0.095296, -0.289995, 0.657437, };
static const float cmu_us_slt_spamf0_accent_frame_77[] = { 
 0.156427, 0.066805, 0.172473, 0.090503, 0.180967, 0.100437, -0.405199, 0.624435, };
static const float cmu_us_slt_spamf0_accent_frame_78[] = { 
 0.150131, 0.070826, 0.176174, 0.096977, 0.205211, 0.094633, -0.211609, 0.598295, };
static const float cmu_us_slt_spamf0_accent_frame_79[] = { 
 0.142222, 0.067466, 0.158772, 0.093788, 0.193054, 0.090226, -0.099726, 0.682883, };
static const float cmu_us_slt_spamf0_accent_frame_80[] = { 
 0.147781, 0.067209, 0.161755, 0.080919, 0.181714, 0.101759, -0.376303, 0.621855, };
static const float cmu_us_slt_spamf0_accent_frame_81[] = { 
 0.161862, 0.059619, 0.193696, 0.093897, 0.207067, 0.093629, -0.215033, 0.597973, };
static const float cmu_us_slt_spamf0_accent_frame_82[] = { 
 0.148032, 0.064870, 0.181896, 0.091256, 0.201270, 0.078881, 0.022864, 0.526746, };
static const float cmu_us_slt_spamf0_accent_frame_83[] = { 
 0.140721, 0.065933, 0.169546, 0.098279, 0.201182, 0.081349, -0.130415, 0.597141, };
static const float cmu_us_slt_spamf0_accent_frame_84[] = { 
 0.156099, 0.063507, 0.186476, 0.090967, 0.202427, 0.086459, -0.082795, 0.604727, };
static const float cmu_us_slt_spamf0_accent_frame_85[] = { 
 0.145165, 0.072768, 0.163882, 0.102211, 0.195348, 0.101778, -0.251659, 0.667685, };
static const float cmu_us_slt_spamf0_accent_frame_86[] = { 
 0.182459, 0.073478, 0.209295, 0.103284, 0.214267, 0.116424, -0.385902, 0.572763, };
static const float cmu_us_slt_spamf0_accent_frame_87[] = { 
 0.175347, 0.066141, 0.208963, 0.093776, 0.226624, 0.111730, -0.217950, 0.598454, };
static const float cmu_us_slt_spamf0_accent_frame_88[] = { 
 0.166538, 0.064317, 0.192313, 0.092662, 0.199877, 0.101710, -0.402789, 0.560747, };
static const float cmu_us_slt_spamf0_accent_frame_89[] = { 
 0.162955, 0.063953, 0.193249, 0.092220, 0.205904, 0.092983, -0.183052, 0.602141, };
static const float cmu_us_slt_spamf0_accent_frame_90[] = { 
 0.172636, 0.066384, 0.210392, 0.101202, 0.222517, 0.104281, -0.293025, 0.546542, };
static const float cmu_us_slt_spamf0_accent_frame_91[] = { 
 0.180395, 0.064260, 0.210762, 0.102720, 0.233362, 0.097043, -0.057987, 0.632807, };
static const float cmu_us_slt_spamf0_accent_frame_92[] = { 
 0.189469, 0.061675, 0.240267, 0.094252, 0.235098, 0.102816, -0.200234, 0.493996, };


const float * const cmu_us_slt_spamf0_accent_vectors[] = {
   cmu_us_slt_spamf0_accent_frame_0,
   cmu_us_slt_spamf0_accent_frame_1,
   cmu_us_slt_spamf0_accent_frame_2,
   cmu_us_slt_spamf0_accent_frame_3,
   cmu_us_slt_spamf0_accent_frame_4,
   cmu_us_slt_spamf0_accent_frame_5,
   cmu_us_slt_spamf0_accent_frame_6,
   cmu_us_slt_spamf0_accent_frame_7,
   cmu_us_slt_spamf0_accent_frame_8,
   cmu_us_slt_spamf0_accent_frame_9,
   cmu_us_slt_spamf0_accent_frame_10,
   cmu_us_slt_spamf0_accent_frame_11,
   cmu_us_slt_spamf0_accent_frame_12,
   cmu_us_slt_spamf0_accent_frame_13,
   cmu_us_slt_spamf0_accent_frame_14,
   cmu_us_slt_spamf0_accent_frame_15,
   cmu_us_slt_spamf0_accent_frame_16,
   cmu_us_slt_spamf0_accent_frame_17,
   cmu_us_slt_spamf0_accent_frame_18,
   cmu_us_slt_spamf0_accent_frame_19,
   cmu_us_slt_spamf0_accent_frame_20,
   cmu_us_slt_spamf0_accent_frame_21,
   cmu_us_slt_spamf0_accent_frame_22,
   cmu_us_slt_spamf0_accent_frame_23,
   cmu_us_slt_spamf0_accent_frame_24,
   cmu_us_slt_spamf0_accent_frame_25,
   cmu_us_slt_spamf0_accent_frame_26,
   cmu_us_slt_spamf0_accent_frame_27,
   cmu_us_slt_spamf0_accent_frame_28,
   cmu_us_slt_spamf0_accent_frame_29,
   cmu_us_slt_spamf0_accent_frame_30,
   cmu_us_slt_spamf0_accent_frame_31,
   cmu_us_slt_spamf0_accent_frame_32,
   cmu_us_slt_spamf0_accent_frame_33,
   cmu_us_slt_spamf0_accent_frame_34,
   cmu_us_slt_spamf0_accent_frame_35,
   cmu_us_slt_spamf0_accent_frame_36,
   cmu_us_slt_spamf0_accent_frame_37,
   cmu_us_slt_spamf0_accent_frame_38,
   cmu_us_slt_spamf0_accent_frame_39,
   cmu_us_slt_spamf0_accent_frame_40,
   cmu_us_slt_spamf0_accent_frame_41,
   cmu_us_slt_spamf0_accent_frame_42,
   cmu_us_slt_spamf0_accent_frame_43,
   cmu_us_slt_spamf0_accent_frame_44,
   cmu_us_slt_spamf0_accent_frame_45,
   cmu_us_slt_spamf0_accent_frame_46,
   cmu_us_slt_spamf0_accent_frame_47,
   cmu_us_slt_spamf0_accent_frame_48,
   cmu_us_slt_spamf0_accent_frame_49,
   cmu_us_slt_spamf0_accent_frame_50,
   cmu_us_slt_spamf0_accent_frame_51,
   cmu_us_slt_spamf0_accent_frame_52,
   cmu_us_slt_spamf0_accent_frame_53,
   cmu_us_slt_spamf0_accent_frame_54,
   cmu_us_slt_spamf0_accent_frame_55,
   cmu_us_slt_spamf0_accent_frame_56,
   cmu_us_slt_spamf0_accent_frame_57,
   cmu_us_slt_spamf0_accent_frame_58,
   cmu_us_slt_spamf0_accent_frame_59,
   cmu_us_slt_spamf0_accent_frame_60,
   cmu_us_slt_spamf0_accent_frame_61,
   cmu_us_slt_spamf0_accent_frame_62,
   cmu_us_slt_spamf0_accent_frame_63,
   cmu_us_slt_spamf0_accent_frame_64,
   cmu_us_slt_spamf0_accent_frame_65,
   cmu_us_slt_spamf0_accent_frame_66,
   cmu_us_slt_spamf0_accent_frame_67,
   cmu_us_slt_spamf0_accent_frame_68,
   cmu_us_slt_spamf0_accent_frame_69,
   cmu_us_slt_spamf0_accent_frame_70,
   cmu_us_slt_spamf0_accent_frame_71,
   cmu_us_slt_spamf0_accent_frame_72,
   cmu_us_slt_spamf0_accent_frame_73,
   cmu_us_slt_spamf0_accent_frame_74,
   cmu_us_slt_spamf0_accent_frame_75,
   cmu_us_slt_spamf0_accent_frame_76,
   cmu_us_slt_spamf0_accent_frame_77,
   cmu_us_slt_spamf0_accent_frame_78,
   cmu_us_slt_spamf0_accent_frame_79,
   cmu_us_slt_spamf0_accent_frame_80,
   cmu_us_slt_spamf0_accent_frame_81,
   cmu_us_slt_spamf0_accent_frame_82,
   cmu_us_slt_spamf0_accent_frame_83,
   cmu_us_slt_spamf0_accent_frame_84,
   cmu_us_slt_spamf0_accent_frame_85,
   cmu_us_slt_spamf0_accent_frame_86,
   cmu_us_slt_spamf0_accent_frame_87,
   cmu_us_slt_spamf0_accent_frame_88,
   cmu_us_slt_spamf0_accent_frame_89,
   cmu_us_slt_spamf0_accent_frame_90,
   cmu_us_slt_spamf0_accent_frame_91,
   cmu_us_slt_spamf0_accent_frame_92,
};

