/*****************************************************/
/**  Autogenerated Spam accent vectors for cmu_us_awb   */
/*****************************************************/
static const float cmu_us_awb_spamf0_accent_frame_0[] = { 
 0.310145, 0.135173, 0.317101, 0.140378, 0.249050, 0.085550, -0.677019, 0.491599, };
static const float cmu_us_awb_spamf0_accent_frame_1[] = { 
 0.308431, 0.143355, 0.303835, 0.153629, 0.232907, 0.091555, -0.879809, 0.357563, };
static const float cmu_us_awb_spamf0_accent_frame_2[] = { 
 0.382088, 0.097130, 0.391424, 0.104289, 0.282949, 0.088935, -0.856800, 0.249825, };
static const float cmu_us_awb_spamf0_accent_frame_3[] = { 
 0.381540, 0.119729, 0.397182, 0.128880, 0.280732, 0.085409, -0.746685, 0.425626, };
static const float cmu_us_awb_spamf0_accent_frame_4[] = { 
 0.366156, 0.113505, 0.381494, 0.124988, 0.278940, 0.095520, -0.790768, 0.329323, };
static const float cmu_us_awb_spamf0_accent_frame_5[] = { 
 0.437531, 0.110365, 0.465314, 0.145198, 0.320879, 0.089381, -0.813203, 0.239134, };
static const float cmu_us_awb_spamf0_accent_frame_6[] = { 
 0.473282, 0.101635, 0.539424, 0.154030, 0.372341, 0.081330, -0.643099, 0.299461, };
static const float cmu_us_awb_spamf0_accent_frame_7[] = { 
 0.446013, 0.103413, 0.483341, 0.149282, 0.342487, 0.085412, -0.733833, 0.313836, };
static const float cmu_us_awb_spamf0_accent_frame_8[] = { 
 0.490556, 0.099360, 0.572804, 0.152194, 0.383825, 0.076916, -0.620001, 0.248565, };
static const float cmu_us_awb_spamf0_accent_frame_9[] = { 
 0.351863, 0.109571, 0.417444, 0.150739, 0.323384, 0.101641, -0.508669, 0.389005, };
static const float cmu_us_awb_spamf0_accent_frame_10[] = { 
 0.147512, 0.082695, 0.137747, 0.080462, 0.166864, 0.078066, -0.886728, 0.309682, };
static const float cmu_us_awb_spamf0_accent_frame_11[] = { 
 0.125632, 0.082746, 0.120871, 0.082483, 0.156084, 0.075210, -0.680823, 0.555793, };
static const float cmu_us_awb_spamf0_accent_frame_12[] = { 
 0.127863, 0.078396, 0.132220, 0.087395, 0.166817, 0.072206, -0.455580, 0.669947, };
static const float cmu_us_awb_spamf0_accent_frame_13[] = { 
 0.095097, 0.076188, 0.089980, 0.074630, 0.127414, 0.071414, -0.402913, 0.785961, };
static const float cmu_us_awb_spamf0_accent_frame_14[] = { 
 0.112474, 0.084506, 0.114181, 0.094667, 0.148123, 0.072573, -0.205290, 0.787421, };
static const float cmu_us_awb_spamf0_accent_frame_15[] = { 
 0.133970, 0.078302, 0.137921, 0.087967, 0.165847, 0.070701, -0.413101, 0.685478, };
static const float cmu_us_awb_spamf0_accent_frame_16[] = { 
 0.077524, 0.052305, 0.071484, 0.052403, 0.124080, 0.063911, -0.557405, 0.745501, };
static const float cmu_us_awb_spamf0_accent_frame_17[] = { 
 0.065036, 0.048791, 0.063009, 0.048433, 0.121720, 0.053397, -0.253287, 0.777804, };
static const float cmu_us_awb_spamf0_accent_frame_18[] = { 
 0.070521, 0.053508, 0.070340, 0.055695, 0.123794, 0.065253, -0.133805, 0.808716, };
static const float cmu_us_awb_spamf0_accent_frame_19[] = { 
 0.100877, 0.070746, 0.103318, 0.078718, 0.146146, 0.063168, -0.208106, 0.771109, };
static const float cmu_us_awb_spamf0_accent_frame_20[] = { 
 0.123567, 0.065422, 0.106556, 0.062684, 0.149323, 0.070390, -0.794458, 0.550207, };
static const float cmu_us_awb_spamf0_accent_frame_21[] = { 
 0.131756, 0.079170, 0.131315, 0.089192, 0.168400, 0.077522, -0.584881, 0.619532, };
static const float cmu_us_awb_spamf0_accent_frame_22[] = { 
 0.175418, 0.085904, 0.180698, 0.089962, 0.184204, 0.065696, -0.682303, 0.435350, };
static const float cmu_us_awb_spamf0_accent_frame_23[] = { 
 0.154051, 0.079002, 0.163685, 0.090756, 0.185983, 0.073270, -0.527605, 0.553712, };
static const float cmu_us_awb_spamf0_accent_frame_24[] = { 
 0.138873, 0.080414, 0.145821, 0.089857, 0.173644, 0.071177, -0.398061, 0.642472, };
static const float cmu_us_awb_spamf0_accent_frame_25[] = { 
 0.157248, 0.092030, 0.159823, 0.102671, 0.171599, 0.077468, -0.596797, 0.606241, };
static const float cmu_us_awb_spamf0_accent_frame_26[] = { 
 0.125707, 0.075371, 0.125774, 0.080310, 0.162251, 0.061623, -0.444473, 0.673993, };
static const float cmu_us_awb_spamf0_accent_frame_27[] = { 
 0.145551, 0.089134, 0.156455, 0.102395, 0.194590, 0.074926, -0.202569, 0.684747, };
static const float cmu_us_awb_spamf0_accent_frame_28[] = { 
 0.120053, 0.078927, 0.123656, 0.082345, 0.169188, 0.066881, -0.397705, 0.644239, };
static const float cmu_us_awb_spamf0_accent_frame_29[] = { 
 0.152983, 0.091622, 0.160511, 0.099618, 0.184682, 0.076514, -0.353584, 0.670069, };
static const float cmu_us_awb_spamf0_accent_frame_30[] = { 
 0.145004, 0.080557, 0.152019, 0.088773, 0.180993, 0.070632, -0.097832, 0.737100, };
static const float cmu_us_awb_spamf0_accent_frame_31[] = { 
 0.164569, 0.082308, 0.176051, 0.087785, 0.187342, 0.067516, -0.432643, 0.576153, };
static const float cmu_us_awb_spamf0_accent_frame_32[] = { 
 0.142612, 0.077440, 0.153374, 0.091240, 0.183939, 0.066260, -0.059921, 0.700738, };
static const float cmu_us_awb_spamf0_accent_frame_33[] = { 
 0.136491, 0.081796, 0.141383, 0.088905, 0.174568, 0.066218, -0.251785, 0.721007, };
static const float cmu_us_awb_spamf0_accent_frame_34[] = { 
 0.154714, 0.079653, 0.168934, 0.089804, 0.197704, 0.061180, 0.056389, 0.620399, };
static const float cmu_us_awb_spamf0_accent_frame_35[] = { 
 0.113170, 0.073165, 0.122265, 0.091499, 0.169281, 0.070400, 0.082918, 0.709051, };
static const float cmu_us_awb_spamf0_accent_frame_36[] = { 
 0.111229, 0.069938, 0.115563, 0.078543, 0.161585, 0.068182, -0.240893, 0.731468, };
static const float cmu_us_awb_spamf0_accent_frame_37[] = { 
 0.147322, 0.074110, 0.153931, 0.081965, 0.189129, 0.064489, -0.147578, 0.721504, };
static const float cmu_us_awb_spamf0_accent_frame_38[] = { 
 0.141652, 0.072408, 0.158010, 0.088309, 0.184663, 0.065113, -0.038845, 0.676127, };
static const float cmu_us_awb_spamf0_accent_frame_39[] = { 
 0.134882, 0.074240, 0.145219, 0.096362, 0.180430, 0.068481, -0.068344, 0.731738, };
static const float cmu_us_awb_spamf0_accent_frame_40[] = { 
 0.125000, 0.072675, 0.136973, 0.088269, 0.172247, 0.076281, -0.333642, 0.646038, };
static const float cmu_us_awb_spamf0_accent_frame_41[] = { 
 0.144746, 0.075594, 0.151323, 0.089742, 0.181943, 0.075518, -0.496456, 0.610682, };
static const float cmu_us_awb_spamf0_accent_frame_42[] = { 
 0.166404, 0.088312, 0.180167, 0.103756, 0.193126, 0.083202, -0.687243, 0.387577, };
static const float cmu_us_awb_spamf0_accent_frame_43[] = { 
 0.160388, 0.071073, 0.170853, 0.094263, 0.181588, 0.069530, -0.454976, 0.649867, };
static const float cmu_us_awb_spamf0_accent_frame_44[] = { 
 0.178070, 0.082591, 0.194115, 0.110933, 0.194899, 0.082268, -0.566044, 0.514007, };
static const float cmu_us_awb_spamf0_accent_frame_45[] = { 
 0.172236, 0.081905, 0.192205, 0.110065, 0.199623, 0.066990, -0.456266, 0.548630, };
static const float cmu_us_awb_spamf0_accent_frame_46[] = { 
 0.196172, 0.078609, 0.214974, 0.095059, 0.221996, 0.070193, -0.349781, 0.596635, };
static const float cmu_us_awb_spamf0_accent_frame_47[] = { 
 0.182034, 0.080521, 0.200557, 0.105519, 0.206201, 0.076306, -0.628523, 0.436622, };
static const float cmu_us_awb_spamf0_accent_frame_48[] = { 
 0.148313, 0.089090, 0.159458, 0.103588, 0.180575, 0.072162, -0.236695, 0.678008, };
static const float cmu_us_awb_spamf0_accent_frame_49[] = { 
 0.141891, 0.092242, 0.146829, 0.099361, 0.176648, 0.068782, -0.198017, 0.726331, };
static const float cmu_us_awb_spamf0_accent_frame_50[] = { 
 0.139181, 0.077227, 0.139119, 0.086780, 0.175405, 0.062933, 0.190199, 0.740534, };
static const float cmu_us_awb_spamf0_accent_frame_51[] = { 
 0.159744, 0.078318, 0.161830, 0.080190, 0.193260, 0.059206, 0.213602, 0.679924, };
static const float cmu_us_awb_spamf0_accent_frame_52[] = { 
 0.163403, 0.080555, 0.172243, 0.092421, 0.207207, 0.061240, 0.361177, 0.556733, };
static const float cmu_us_awb_spamf0_accent_frame_53[] = { 
 0.097729, 0.063024, 0.101698, 0.069443, 0.156614, 0.057339, 0.169319, 0.697274, };
static const float cmu_us_awb_spamf0_accent_frame_54[] = { 
 0.151428, 0.083377, 0.153226, 0.088139, 0.171654, 0.056091, -0.613868, 0.535870, };
static const float cmu_us_awb_spamf0_accent_frame_55[] = { 
 0.129542, 0.074549, 0.140357, 0.086360, 0.181864, 0.067442, -0.154543, 0.692211, };
static const float cmu_us_awb_spamf0_accent_frame_56[] = { 
 0.092943, 0.058786, 0.093349, 0.062689, 0.145325, 0.059220, -0.116537, 0.756503, };
static const float cmu_us_awb_spamf0_accent_frame_57[] = { 
 0.192411, 0.079619, 0.211923, 0.101884, 0.210907, 0.081488, -0.334522, 0.657718, };
static const float cmu_us_awb_spamf0_accent_frame_58[] = { 
 0.157958, 0.072786, 0.178301, 0.090670, 0.203922, 0.059306, -0.073806, 0.609326, };
static const float cmu_us_awb_spamf0_accent_frame_59[] = { 
 0.160497, 0.084851, 0.173706, 0.107104, 0.182491, 0.083127, -0.596397, 0.503360, };
static const float cmu_us_awb_spamf0_accent_frame_60[] = { 
 0.157575, 0.081566, 0.193676, 0.106603, 0.211009, 0.073210, -0.125618, 0.526768, };
static const float cmu_us_awb_spamf0_accent_frame_61[] = { 
 0.198011, 0.084911, 0.255364, 0.124093, 0.242654, 0.073881, -0.061868, 0.422549, };
static const float cmu_us_awb_spamf0_accent_frame_62[] = { 
 0.185152, 0.078632, 0.207170, 0.098120, 0.212183, 0.056826, 0.249748, 0.539244, };
static const float cmu_us_awb_spamf0_accent_frame_63[] = { 
 0.188929, 0.079215, 0.216687, 0.103710, 0.226369, 0.062313, 0.119708, 0.542892, };
static const float cmu_us_awb_spamf0_accent_frame_64[] = { 
 0.159262, 0.073063, 0.166390, 0.085347, 0.208572, 0.064177, 0.420850, 0.503756, };
static const float cmu_us_awb_spamf0_accent_frame_65[] = { 
 0.179171, 0.069636, 0.201864, 0.087882, 0.227422, 0.057501, 0.361463, 0.395921, };
static const float cmu_us_awb_spamf0_accent_frame_66[] = { 
 0.190454, 0.083428, 0.218961, 0.103496, 0.232811, 0.060900, 0.196745, 0.480843, };
static const float cmu_us_awb_spamf0_accent_frame_67[] = { 
 0.182400, 0.080406, 0.193718, 0.082800, 0.211029, 0.071436, -0.315926, 0.660274, };
static const float cmu_us_awb_spamf0_accent_frame_68[] = { 
 0.160768, 0.075055, 0.175424, 0.090988, 0.196217, 0.068362, -0.324209, 0.643026, };
static const float cmu_us_awb_spamf0_accent_frame_69[] = { 
 0.185692, 0.086715, 0.207814, 0.106419, 0.215014, 0.075931, -0.178873, 0.641450, };
static const float cmu_us_awb_spamf0_accent_frame_70[] = { 
 0.177752, 0.095486, 0.199292, 0.112025, 0.215751, 0.071505, -0.112718, 0.596312, };
static const float cmu_us_awb_spamf0_accent_frame_71[] = { 
 0.213938, 0.097456, 0.237324, 0.120270, 0.238896, 0.078498, -0.158204, 0.657556, };
static const float cmu_us_awb_spamf0_accent_frame_72[] = { 
 0.187416, 0.080944, 0.211756, 0.101882, 0.220707, 0.068678, -0.070347, 0.612622, };
static const float cmu_us_awb_spamf0_accent_frame_73[] = { 
 0.205521, 0.075355, 0.244701, 0.102636, 0.225428, 0.062941, -0.197058, 0.534468, };
static const float cmu_us_awb_spamf0_accent_frame_74[] = { 
 0.196434, 0.084528, 0.219606, 0.106680, 0.227817, 0.064625, -0.006390, 0.634567, };
static const float cmu_us_awb_spamf0_accent_frame_75[] = { 
 0.224384, 0.079767, 0.258758, 0.109049, 0.255803, 0.071758, -0.041921, 0.603880, };
static const float cmu_us_awb_spamf0_accent_frame_76[] = { 
 0.242239, 0.088497, 0.289788, 0.119932, 0.255600, 0.080713, -0.201742, 0.492002, };
static const float cmu_us_awb_spamf0_accent_frame_77[] = { 
 0.176374, 0.083845, 0.189303, 0.093346, 0.223572, 0.057932, 0.170631, 0.616112, };
static const float cmu_us_awb_spamf0_accent_frame_78[] = { 
 0.161974, 0.080861, 0.186041, 0.100614, 0.209986, 0.068193, -0.082965, 0.579950, };
static const float cmu_us_awb_spamf0_accent_frame_79[] = { 
 0.200120, 0.073561, 0.230471, 0.096543, 0.235655, 0.055549, 0.203574, 0.477425, };
static const float cmu_us_awb_spamf0_accent_frame_80[] = { 
 0.213420, 0.084249, 0.247854, 0.111626, 0.246347, 0.056969, 0.171847, 0.509600, };
static const float cmu_us_awb_spamf0_accent_frame_81[] = { 
 0.198599, 0.087464, 0.234312, 0.114181, 0.237129, 0.063017, 0.022840, 0.546876, };
static const float cmu_us_awb_spamf0_accent_frame_82[] = { 
 0.202738, 0.083693, 0.254467, 0.113382, 0.240550, 0.065666, -0.040884, 0.429077, };
static const float cmu_us_awb_spamf0_accent_frame_83[] = { 
 0.224075, 0.091077, 0.267725, 0.122288, 0.259880, 0.071221, 0.024749, 0.524956, };
static const float cmu_us_awb_spamf0_accent_frame_84[] = { 
 0.182650, 0.081144, 0.201109, 0.104255, 0.219565, 0.074974, -0.324075, 0.630465, };
static const float cmu_us_awb_spamf0_accent_frame_85[] = { 
 0.192676, 0.081549, 0.216745, 0.109681, 0.227920, 0.078396, -0.390718, 0.579211, };
static const float cmu_us_awb_spamf0_accent_frame_86[] = { 
 0.194686, 0.079562, 0.225192, 0.107799, 0.222597, 0.080447, -0.508952, 0.472927, };
static const float cmu_us_awb_spamf0_accent_frame_87[] = { 
 0.182236, 0.086589, 0.180633, 0.097041, 0.188521, 0.082565, -0.799024, 0.345127, };
static const float cmu_us_awb_spamf0_accent_frame_88[] = { 
 0.154499, 0.080610, 0.158691, 0.086726, 0.193638, 0.064670, -0.284840, 0.687705, };
static const float cmu_us_awb_spamf0_accent_frame_89[] = { 
 0.157620, 0.082400, 0.167492, 0.092933, 0.205923, 0.067817, -0.046342, 0.684403, };
static const float cmu_us_awb_spamf0_accent_frame_90[] = { 
 0.177877, 0.075025, 0.216141, 0.103958, 0.213782, 0.070300, -0.136546, 0.535599, };
static const float cmu_us_awb_spamf0_accent_frame_91[] = { 
 0.158817, 0.066077, 0.176681, 0.079135, 0.215247, 0.057483, 0.295813, 0.464640, };
static const float cmu_us_awb_spamf0_accent_frame_92[] = { 
 0.176328, 0.082889, 0.213469, 0.114966, 0.219727, 0.077637, -0.143505, 0.541789, };
static const float cmu_us_awb_spamf0_accent_frame_93[] = { 
 0.217379, 0.082502, 0.267887, 0.108064, 0.253149, 0.072148, -0.137715, 0.471289, };
static const float cmu_us_awb_spamf0_accent_frame_94[] = { 
 0.180854, 0.081525, 0.209363, 0.112735, 0.215707, 0.077955, -0.321267, 0.557197, };


const float * const cmu_us_awb_spamf0_accent_vectors[] = {
   cmu_us_awb_spamf0_accent_frame_0,
   cmu_us_awb_spamf0_accent_frame_1,
   cmu_us_awb_spamf0_accent_frame_2,
   cmu_us_awb_spamf0_accent_frame_3,
   cmu_us_awb_spamf0_accent_frame_4,
   cmu_us_awb_spamf0_accent_frame_5,
   cmu_us_awb_spamf0_accent_frame_6,
   cmu_us_awb_spamf0_accent_frame_7,
   cmu_us_awb_spamf0_accent_frame_8,
   cmu_us_awb_spamf0_accent_frame_9,
   cmu_us_awb_spamf0_accent_frame_10,
   cmu_us_awb_spamf0_accent_frame_11,
   cmu_us_awb_spamf0_accent_frame_12,
   cmu_us_awb_spamf0_accent_frame_13,
   cmu_us_awb_spamf0_accent_frame_14,
   cmu_us_awb_spamf0_accent_frame_15,
   cmu_us_awb_spamf0_accent_frame_16,
   cmu_us_awb_spamf0_accent_frame_17,
   cmu_us_awb_spamf0_accent_frame_18,
   cmu_us_awb_spamf0_accent_frame_19,
   cmu_us_awb_spamf0_accent_frame_20,
   cmu_us_awb_spamf0_accent_frame_21,
   cmu_us_awb_spamf0_accent_frame_22,
   cmu_us_awb_spamf0_accent_frame_23,
   cmu_us_awb_spamf0_accent_frame_24,
   cmu_us_awb_spamf0_accent_frame_25,
   cmu_us_awb_spamf0_accent_frame_26,
   cmu_us_awb_spamf0_accent_frame_27,
   cmu_us_awb_spamf0_accent_frame_28,
   cmu_us_awb_spamf0_accent_frame_29,
   cmu_us_awb_spamf0_accent_frame_30,
   cmu_us_awb_spamf0_accent_frame_31,
   cmu_us_awb_spamf0_accent_frame_32,
   cmu_us_awb_spamf0_accent_frame_33,
   cmu_us_awb_spamf0_accent_frame_34,
   cmu_us_awb_spamf0_accent_frame_35,
   cmu_us_awb_spamf0_accent_frame_36,
   cmu_us_awb_spamf0_accent_frame_37,
   cmu_us_awb_spamf0_accent_frame_38,
   cmu_us_awb_spamf0_accent_frame_39,
   cmu_us_awb_spamf0_accent_frame_40,
   cmu_us_awb_spamf0_accent_frame_41,
   cmu_us_awb_spamf0_accent_frame_42,
   cmu_us_awb_spamf0_accent_frame_43,
   cmu_us_awb_spamf0_accent_frame_44,
   cmu_us_awb_spamf0_accent_frame_45,
   cmu_us_awb_spamf0_accent_frame_46,
   cmu_us_awb_spamf0_accent_frame_47,
   cmu_us_awb_spamf0_accent_frame_48,
   cmu_us_awb_spamf0_accent_frame_49,
   cmu_us_awb_spamf0_accent_frame_50,
   cmu_us_awb_spamf0_accent_frame_51,
   cmu_us_awb_spamf0_accent_frame_52,
   cmu_us_awb_spamf0_accent_frame_53,
   cmu_us_awb_spamf0_accent_frame_54,
   cmu_us_awb_spamf0_accent_frame_55,
   cmu_us_awb_spamf0_accent_frame_56,
   cmu_us_awb_spamf0_accent_frame_57,
   cmu_us_awb_spamf0_accent_frame_58,
   cmu_us_awb_spamf0_accent_frame_59,
   cmu_us_awb_spamf0_accent_frame_60,
   cmu_us_awb_spamf0_accent_frame_61,
   cmu_us_awb_spamf0_accent_frame_62,
   cmu_us_awb_spamf0_accent_frame_63,
   cmu_us_awb_spamf0_accent_frame_64,
   cmu_us_awb_spamf0_accent_frame_65,
   cmu_us_awb_spamf0_accent_frame_66,
   cmu_us_awb_spamf0_accent_frame_67,
   cmu_us_awb_spamf0_accent_frame_68,
   cmu_us_awb_spamf0_accent_frame_69,
   cmu_us_awb_spamf0_accent_frame_70,
   cmu_us_awb_spamf0_accent_frame_71,
   cmu_us_awb_spamf0_accent_frame_72,
   cmu_us_awb_spamf0_accent_frame_73,
   cmu_us_awb_spamf0_accent_frame_74,
   cmu_us_awb_spamf0_accent_frame_75,
   cmu_us_awb_spamf0_accent_frame_76,
   cmu_us_awb_spamf0_accent_frame_77,
   cmu_us_awb_spamf0_accent_frame_78,
   cmu_us_awb_spamf0_accent_frame_79,
   cmu_us_awb_spamf0_accent_frame_80,
   cmu_us_awb_spamf0_accent_frame_81,
   cmu_us_awb_spamf0_accent_frame_82,
   cmu_us_awb_spamf0_accent_frame_83,
   cmu_us_awb_spamf0_accent_frame_84,
   cmu_us_awb_spamf0_accent_frame_85,
   cmu_us_awb_spamf0_accent_frame_86,
   cmu_us_awb_spamf0_accent_frame_87,
   cmu_us_awb_spamf0_accent_frame_88,
   cmu_us_awb_spamf0_accent_frame_89,
   cmu_us_awb_spamf0_accent_frame_90,
   cmu_us_awb_spamf0_accent_frame_91,
   cmu_us_awb_spamf0_accent_frame_92,
   cmu_us_awb_spamf0_accent_frame_93,
   cmu_us_awb_spamf0_accent_frame_94,
};

