/*******************************************************/
/**  Autogenerated phoneset trees for cmu_indic    */
/*******************************************************/

#include "cst_string.h"
#include "cst_phoneset.h"
extern const cst_phoneset cmu_indic_phoneset;


static const char * const cmu_indic_featnames[] = {
 "clst",
 "vc",
 "vlng",
 "vheight",
 "vfront",
 "vrnd",
 "ctype",
 "cplace",
 "cvox",
 "asp",
 "nuk",
 NULL };

static const char * const cmu_indic_phonenames[] = {
 "pau",
 "A",
 "A:",
 "i",
 "i:",
 "u",
 "uy",
 "u:",
 "9r=",
 "lr=",
 "E",
 "e",
 "e:",
 "aI",
 "o",
 "o:",
 "aU",
 "M",
 "h",
 "ay",
 "ow",
 "k",
 "kh",
 "g",
 "gh",
 "N",
 "c",
 "ch",
 "J",
 "Jh",
 "n~",
 "tr",
 "tR",
 "dr",
 "dR",
 "nr",
 "tB",
 "tBh",
 "dB",
 "dBh",
 "nB",
 "n",
 "p",
 "ph",
 "b",
 "bh",
 "m",
 "j",
 "9r",
 "l",
 "lr",
 "zr",
 "v",
 "c}",
 "sr",
 "s",
 "hv",
 "q",
 "x",
 "G",
 "z",
 "rr",
 "rrh",
 "f",
 "dh",
 "B",
 "nX",
 "Anas",
 "A:nas",
 "inas",
 "i:nas",
 "unas",
 "u:nas",
 "enas",
 "e:nas",
 "aInas",
 "onas",
 "o:nas",
 "aUnas",
 "aynas",
 "ownas",
 "aa",
 "ae",
 "ah",
 "ao",
 "aw",
 "ax",
 "axr",
 "d",
 "eh",
 "er",
 "ey",
 "hh",
 "ih",
 "iy",
 "jh",
 "ng",
 "oy",
 "r",
 "sh",
 "t",
 "th",
 "uh",
 "uw",
 "w",
 "y",
 "zh",
 NULL };

static const int cmu_indic_fv_000[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_indic_fv_001[] = { 0, 2, 3, 4, 4, 0, 1, 1, 1, 0, 1,   -1 };
static const int cmu_indic_fv_002[] = { 0, 2, 5, 6, 4, 0, 1, 1, 1, 0, 1,   -1 };
static const int cmu_indic_fv_003[] = { 0, 2, 3, 7, 7, 0, 1, 1, 1, 0, 1,   -1 };
static const int cmu_indic_fv_004[] = { 0, 2, 5, 7, 7, 0, 1, 1, 1, 0, 1,   -1 };
static const int cmu_indic_fv_005[] = { 0, 2, 3, 7, 6, 2, 1, 1, 1, 0, 1,   -1 };
static const int cmu_indic_fv_006[] = { 0, 2, 3, 7, 6, 0, 1, 1, 1, 0, 1,   -1 };
static const int cmu_indic_fv_007[] = { 0, 2, 5, 7, 6, 2, 1, 1, 1, 0, 1,   -1 };
static const int cmu_indic_fv_008[] = { 0, 2, 3, 7, 6, 0, 1, 1, 1, 0, 1,   -1 };
static const int cmu_indic_fv_009[] = { 0, 2, 8, 4, 6, 0, 1, 1, 1, 0, 1,   -1 };
static const int cmu_indic_fv_010[] = { 0, 2, 9, 4, 7, 0, 1, 1, 1, 0, 1,   -1 };
static const int cmu_indic_fv_011[] = { 0, 2, 3, 4, 7, 0, 1, 1, 1, 0, 1,   -1 };
static const int cmu_indic_fv_012[] = { 0, 2, 5, 4, 7, 0, 1, 1, 1, 0, 1,   -1 };
static const int cmu_indic_fv_013[] = { 0, 2, 8, 4, 7, 0, 1, 1, 1, 0, 1,   -1 };
static const int cmu_indic_fv_014[] = { 0, 2, 3, 4, 6, 2, 1, 1, 1, 0, 1,   -1 };
static const int cmu_indic_fv_015[] = { 0, 2, 5, 4, 6, 2, 1, 1, 1, 0, 1,   -1 };
static const int cmu_indic_fv_016[] = { 0, 2, 8, 7, 6, 2, 1, 1, 1, 0, 1,   -1 };
static const int cmu_indic_fv_017[] = { 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,   -1 };
static const int cmu_indic_fv_018[] = { 0, 0, 1, 1, 1, 1, 10, 11, 0, 2, 0,   -1 };
static const int cmu_indic_fv_019[] = { 0, 2, 3, 4, 4, 0, 1, 1, 1, 0, 1,   -1 };
static const int cmu_indic_fv_020[] = { 0, 2, 5, 6, 6, 2, 1, 1, 1, 0, 1,   -1 };
static const int cmu_indic_fv_021[] = { 0, 0, 1, 1, 1, 1, 3, 11, 0, 0, 0,   -1 };
static const int cmu_indic_fv_022[] = { 0, 0, 1, 1, 1, 1, 3, 11, 0, 2, 0,   -1 };
static const int cmu_indic_fv_023[] = { 0, 0, 1, 1, 1, 1, 3, 11, 2, 0, 0,   -1 };
static const int cmu_indic_fv_024[] = { 0, 0, 1, 1, 1, 1, 3, 11, 2, 2, 0,   -1 };
static const int cmu_indic_fv_025[] = { 0, 0, 1, 1, 1, 1, 12, 11, 2, 0, 0,   -1 };
static const int cmu_indic_fv_026[] = { 0, 0, 1, 1, 1, 1, 9, 13, 0, 0, 0,   -1 };
static const int cmu_indic_fv_027[] = { 0, 0, 1, 1, 1, 1, 9, 13, 0, 2, 0,   -1 };
static const int cmu_indic_fv_028[] = { 0, 0, 1, 1, 1, 1, 9, 13, 2, 0, 0,   -1 };
static const int cmu_indic_fv_029[] = { 0, 0, 1, 1, 1, 1, 9, 13, 2, 2, 0,   -1 };
static const int cmu_indic_fv_030[] = { 0, 0, 1, 1, 1, 1, 12, 13, 2, 0, 0,   -1 };
static const int cmu_indic_fv_031[] = { 0, 0, 1, 1, 1, 1, 3, 9, 0, 0, 0,   -1 };
static const int cmu_indic_fv_032[] = { 0, 0, 1, 1, 1, 1, 3, 9, 0, 2, 0,   -1 };
static const int cmu_indic_fv_033[] = { 0, 0, 1, 1, 1, 1, 3, 9, 2, 0, 0,   -1 };
static const int cmu_indic_fv_034[] = { 0, 0, 1, 1, 1, 1, 3, 9, 2, 2, 0,   -1 };
static const int cmu_indic_fv_035[] = { 0, 0, 1, 1, 1, 1, 12, 9, 2, 0, 0,   -1 };
static const int cmu_indic_fv_036[] = { 0, 0, 1, 1, 1, 1, 3, 8, 0, 0, 0,   -1 };
static const int cmu_indic_fv_037[] = { 0, 0, 1, 1, 1, 1, 3, 8, 0, 2, 0,   -1 };
static const int cmu_indic_fv_038[] = { 0, 0, 1, 1, 1, 1, 3, 8, 2, 0, 0,   -1 };
static const int cmu_indic_fv_039[] = { 0, 0, 1, 1, 1, 1, 3, 8, 2, 2, 0,   -1 };
static const int cmu_indic_fv_040[] = { 0, 0, 1, 1, 1, 1, 12, 8, 2, 0, 0,   -1 };
static const int cmu_indic_fv_041[] = { 0, 0, 1, 1, 1, 1, 12, 9, 2, 0, 0,   -1 };
static const int cmu_indic_fv_042[] = { 0, 0, 1, 1, 1, 1, 3, 5, 0, 0, 0,   -1 };
static const int cmu_indic_fv_043[] = { 0, 0, 1, 1, 1, 1, 3, 5, 0, 2, 0,   -1 };
static const int cmu_indic_fv_044[] = { 0, 0, 1, 1, 1, 1, 3, 5, 2, 0, 0,   -1 };
static const int cmu_indic_fv_045[] = { 0, 0, 1, 1, 1, 1, 3, 5, 2, 2, 0,   -1 };
static const int cmu_indic_fv_046[] = { 0, 0, 1, 1, 1, 1, 12, 5, 2, 0, 0,   -1 };
static const int cmu_indic_fv_047[] = { 0, 0, 1, 1, 1, 1, 14, 13, 2, 0, 0,   -1 };
static const int cmu_indic_fv_048[] = { 0, 0, 1, 1, 1, 1, 14, 9, 2, 0, 0,   -1 };
static const int cmu_indic_fv_049[] = { 0, 0, 1, 1, 1, 1, 14, 8, 2, 0, 0,   -1 };
static const int cmu_indic_fv_050[] = { 0, 0, 1, 1, 1, 1, 14, 9, 2, 0, 0,   -1 };
static const int cmu_indic_fv_051[] = { 0, 0, 1, 1, 1, 1, 14, 9, 2, 0, 0,   -1 };
static const int cmu_indic_fv_052[] = { 0, 0, 1, 1, 1, 1, 14, 5, 2, 0, 0,   -1 };
static const int cmu_indic_fv_053[] = { 0, 0, 1, 1, 1, 1, 10, 13, 0, 2, 0,   -1 };
static const int cmu_indic_fv_054[] = { 0, 0, 1, 1, 1, 1, 10, 9, 0, 2, 0,   -1 };
static const int cmu_indic_fv_055[] = { 0, 0, 1, 1, 1, 1, 10, 8, 0, 2, 0,   -1 };
static const int cmu_indic_fv_056[] = { 0, 0, 1, 1, 1, 1, 10, 11, 2, 2, 0,   -1 };
static const int cmu_indic_fv_057[] = { 0, 0, 1, 1, 1, 1, 3, 15, 0, 0, 2,   -1 };
static const int cmu_indic_fv_058[] = { 0, 0, 1, 1, 1, 1, 10, 15, 0, 0, 2,   -1 };
static const int cmu_indic_fv_059[] = { 0, 0, 1, 1, 1, 1, 10, 15, 2, 0, 2,   -1 };
static const int cmu_indic_fv_060[] = { 0, 0, 1, 1, 1, 1, 10, 8, 2, 0, 2,   -1 };
static const int cmu_indic_fv_061[] = { 0, 0, 1, 1, 1, 1, 3, 9, 2, 0, 2,   -1 };
static const int cmu_indic_fv_062[] = { 0, 0, 1, 1, 1, 1, 3, 9, 2, 2, 2,   -1 };
static const int cmu_indic_fv_063[] = { 0, 0, 1, 1, 1, 1, 10, 16, 0, 0, 2,   -1 };
static const int cmu_indic_fv_064[] = { 0, 0, 1, 1, 1, 1, 10, 8, 2, 0, 2,   -1 };
static const int cmu_indic_fv_065[] = { 0, 0, 1, 1, 1, 1, 10, 5, 2, 0, 2,   -1 };
static const int cmu_indic_fv_066[] = { 0, 0, 1, 1, 1, 1, 12, 11, 2, 0, 0,   -1 };
static const int cmu_indic_fv_067[] = { 0, 2, 3, 4, 4, 0, 1, 1, 1, 0, 1,   -1 };
static const int cmu_indic_fv_068[] = { 0, 2, 5, 6, 4, 0, 1, 1, 1, 0, 1,   -1 };
static const int cmu_indic_fv_069[] = { 0, 2, 3, 7, 7, 0, 1, 1, 1, 0, 1,   -1 };
static const int cmu_indic_fv_070[] = { 0, 2, 5, 7, 7, 0, 1, 1, 1, 0, 1,   -1 };
static const int cmu_indic_fv_071[] = { 0, 2, 3, 7, 6, 2, 1, 1, 1, 0, 1,   -1 };
static const int cmu_indic_fv_072[] = { 0, 2, 5, 7, 6, 2, 1, 1, 1, 0, 1,   -1 };
static const int cmu_indic_fv_073[] = { 0, 2, 3, 4, 7, 0, 1, 1, 1, 0, 1,   -1 };
static const int cmu_indic_fv_074[] = { 0, 2, 5, 4, 7, 0, 1, 1, 1, 0, 1,   -1 };
static const int cmu_indic_fv_075[] = { 0, 2, 8, 4, 7, 0, 1, 1, 1, 0, 1,   -1 };
static const int cmu_indic_fv_076[] = { 0, 2, 3, 4, 6, 2, 1, 1, 1, 0, 1,   -1 };
static const int cmu_indic_fv_077[] = { 0, 2, 5, 4, 6, 2, 1, 1, 1, 0, 1,   -1 };
static const int cmu_indic_fv_078[] = { 0, 2, 8, 7, 6, 2, 1, 1, 1, 0, 1,   -1 };
static const int cmu_indic_fv_079[] = { 0, 2, 3, 4, 4, 0, 1, 1, 1, 0, 1,   -1 };
static const int cmu_indic_fv_080[] = { 0, 2, 3, 6, 6, 2, 1, 1, 1, 0, 1,   -1 };
static const int cmu_indic_fv_081[] = { 0, 2, 5, 6, 6, 0, 1, 1, 1, 0, 1,   -1 };
static const int cmu_indic_fv_082[] = { 0, 2, 3, 6, 7, 0, 1, 1, 1, 0, 1,   -1 };
static const int cmu_indic_fv_083[] = { 0, 2, 3, 4, 4, 0, 1, 1, 1, 0, 1,   -1 };
static const int cmu_indic_fv_084[] = { 0, 2, 5, 6, 6, 2, 1, 1, 1, 0, 1,   -1 };
static const int cmu_indic_fv_085[] = { 0, 2, 8, 6, 4, 0, 1, 1, 1, 0, 1,   -1 };
static const int cmu_indic_fv_086[] = { 0, 2, 9, 4, 4, 0, 1, 1, 1, 0, 1,   -1 };
static const int cmu_indic_fv_087[] = { 0, 2, 9, 4, 4, 0, 14, 9, 2, 0, 1,   -1 };
static const int cmu_indic_fv_088[] = { 0, 0, 1, 1, 1, 1, 3, 9, 2, 0, 1,   -1 };
static const int cmu_indic_fv_089[] = { 0, 2, 3, 4, 7, 0, 1, 1, 1, 0, 1,   -1 };
static const int cmu_indic_fv_090[] = { 0, 2, 9, 4, 4, 0, 14, 1, 1, 0, 1,   -1 };
static const int cmu_indic_fv_091[] = { 0, 2, 8, 4, 7, 0, 1, 1, 1, 0, 1,   -1 };
static const int cmu_indic_fv_092[] = { 0, 0, 1, 1, 1, 1, 10, 15, 0, 0, 1,   -1 };
static const int cmu_indic_fv_093[] = { 0, 2, 3, 7, 7, 0, 1, 1, 1, 0, 1,   -1 };
static const int cmu_indic_fv_094[] = { 0, 2, 5, 7, 7, 0, 1, 1, 1, 0, 1,   -1 };
static const int cmu_indic_fv_095[] = { 0, 0, 1, 1, 1, 1, 9, 13, 2, 0, 1,   -1 };
static const int cmu_indic_fv_096[] = { 0, 0, 1, 1, 1, 1, 12, 11, 2, 0, 1,   -1 };
static const int cmu_indic_fv_097[] = { 0, 2, 8, 4, 6, 2, 1, 1, 1, 0, 1,   -1 };
static const int cmu_indic_fv_098[] = { 0, 0, 1, 1, 1, 1, 14, 9, 2, 0, 1,   -1 };
static const int cmu_indic_fv_099[] = { 0, 0, 1, 1, 1, 1, 10, 13, 0, 0, 1,   -1 };
static const int cmu_indic_fv_100[] = { 0, 0, 1, 1, 1, 1, 3, 9, 0, 0, 1,   -1 };
static const int cmu_indic_fv_101[] = { 0, 0, 1, 1, 1, 1, 10, 8, 0, 0, 1,   -1 };
static const int cmu_indic_fv_102[] = { 0, 2, 3, 7, 6, 2, 1, 1, 1, 0, 1,   -1 };
static const int cmu_indic_fv_103[] = { 0, 2, 5, 7, 6, 2, 1, 1, 1, 0, 1,   -1 };
static const int cmu_indic_fv_104[] = { 0, 0, 1, 1, 1, 1, 14, 5, 2, 0, 1,   -1 };
static const int cmu_indic_fv_105[] = { 0, 0, 1, 1, 1, 1, 14, 13, 2, 0, 1,   -1 };
static const int cmu_indic_fv_106[] = { 0, 0, 1, 1, 1, 1, 10, 13, 2, 0, 1,   -1 };
static const int cmu_indic_fv_107[] = { 0 };

static const int * const cmu_indic_fvtable[] = {
  cmu_indic_fv_000, 
  cmu_indic_fv_001, 
  cmu_indic_fv_002, 
  cmu_indic_fv_003, 
  cmu_indic_fv_004, 
  cmu_indic_fv_005, 
  cmu_indic_fv_006, 
  cmu_indic_fv_007, 
  cmu_indic_fv_008, 
  cmu_indic_fv_009, 
  cmu_indic_fv_010, 
  cmu_indic_fv_011, 
  cmu_indic_fv_012, 
  cmu_indic_fv_013, 
  cmu_indic_fv_014, 
  cmu_indic_fv_015, 
  cmu_indic_fv_016, 
  cmu_indic_fv_017, 
  cmu_indic_fv_018, 
  cmu_indic_fv_019, 
  cmu_indic_fv_020, 
  cmu_indic_fv_021, 
  cmu_indic_fv_022, 
  cmu_indic_fv_023, 
  cmu_indic_fv_024, 
  cmu_indic_fv_025, 
  cmu_indic_fv_026, 
  cmu_indic_fv_027, 
  cmu_indic_fv_028, 
  cmu_indic_fv_029, 
  cmu_indic_fv_030, 
  cmu_indic_fv_031, 
  cmu_indic_fv_032, 
  cmu_indic_fv_033, 
  cmu_indic_fv_034, 
  cmu_indic_fv_035, 
  cmu_indic_fv_036, 
  cmu_indic_fv_037, 
  cmu_indic_fv_038, 
  cmu_indic_fv_039, 
  cmu_indic_fv_040, 
  cmu_indic_fv_041, 
  cmu_indic_fv_042, 
  cmu_indic_fv_043, 
  cmu_indic_fv_044, 
  cmu_indic_fv_045, 
  cmu_indic_fv_046, 
  cmu_indic_fv_047, 
  cmu_indic_fv_048, 
  cmu_indic_fv_049, 
  cmu_indic_fv_050, 
  cmu_indic_fv_051, 
  cmu_indic_fv_052, 
  cmu_indic_fv_053, 
  cmu_indic_fv_054, 
  cmu_indic_fv_055, 
  cmu_indic_fv_056, 
  cmu_indic_fv_057, 
  cmu_indic_fv_058, 
  cmu_indic_fv_059, 
  cmu_indic_fv_060, 
  cmu_indic_fv_061, 
  cmu_indic_fv_062, 
  cmu_indic_fv_063, 
  cmu_indic_fv_064, 
  cmu_indic_fv_065, 
  cmu_indic_fv_066, 
  cmu_indic_fv_067, 
  cmu_indic_fv_068, 
  cmu_indic_fv_069, 
  cmu_indic_fv_070, 
  cmu_indic_fv_071, 
  cmu_indic_fv_072, 
  cmu_indic_fv_073, 
  cmu_indic_fv_074, 
  cmu_indic_fv_075, 
  cmu_indic_fv_076, 
  cmu_indic_fv_077, 
  cmu_indic_fv_078, 
  cmu_indic_fv_079, 
  cmu_indic_fv_080, 
  cmu_indic_fv_081, 
  cmu_indic_fv_082, 
  cmu_indic_fv_083, 
  cmu_indic_fv_084, 
  cmu_indic_fv_085, 
  cmu_indic_fv_086, 
  cmu_indic_fv_087, 
  cmu_indic_fv_088, 
  cmu_indic_fv_089, 
  cmu_indic_fv_090, 
  cmu_indic_fv_091, 
  cmu_indic_fv_092, 
  cmu_indic_fv_093, 
  cmu_indic_fv_094, 
  cmu_indic_fv_095, 
  cmu_indic_fv_096, 
  cmu_indic_fv_097, 
  cmu_indic_fv_098, 
  cmu_indic_fv_099, 
  cmu_indic_fv_100, 
  cmu_indic_fv_101, 
  cmu_indic_fv_102, 
  cmu_indic_fv_103, 
  cmu_indic_fv_104, 
  cmu_indic_fv_105, 
  cmu_indic_fv_106, 
 cmu_indic_fv_107 };

DEF_STATIC_CONST_VAL_STRING(featval_0,"-");
DEF_STATIC_CONST_VAL_STRING(featval_1,"0");
DEF_STATIC_CONST_VAL_STRING(featval_2,"+");
DEF_STATIC_CONST_VAL_STRING(featval_3,"s");
DEF_STATIC_CONST_VAL_STRING(featval_4,"2");
DEF_STATIC_CONST_VAL_STRING(featval_5,"l");
DEF_STATIC_CONST_VAL_STRING(featval_6,"3");
DEF_STATIC_CONST_VAL_STRING(featval_7,"1");
DEF_STATIC_CONST_VAL_STRING(featval_8,"d");
DEF_STATIC_CONST_VAL_STRING(featval_9,"a");
DEF_STATIC_CONST_VAL_STRING(featval_10,"f");
DEF_STATIC_CONST_VAL_STRING(featval_11,"v");
DEF_STATIC_CONST_VAL_STRING(featval_12,"n");
DEF_STATIC_CONST_VAL_STRING(featval_13,"p");
DEF_STATIC_CONST_VAL_STRING(featval_14,"r");
DEF_STATIC_CONST_VAL_STRING(featval_15,"g");
DEF_STATIC_CONST_VAL_STRING(featval_16,"b");

static const cst_val * const cmu_indic_featvals[] = {
 (cst_val *)&featval_0,
 (cst_val *)&featval_1,
 (cst_val *)&featval_2,
 (cst_val *)&featval_3,
 (cst_val *)&featval_4,
 (cst_val *)&featval_5,
 (cst_val *)&featval_6,
 (cst_val *)&featval_7,
 (cst_val *)&featval_8,
 (cst_val *)&featval_9,
 (cst_val *)&featval_10,
 (cst_val *)&featval_11,
 (cst_val *)&featval_12,
 (cst_val *)&featval_13,
 (cst_val *)&featval_14,
 (cst_val *)&featval_15,
 (cst_val *)&featval_16,
 NULL };

const cst_phoneset cmu_indic_phoneset = {
  "cmu_indic",
  cmu_indic_featnames,
  cmu_indic_featvals,
  cmu_indic_phonenames,
  "pau",
  107,
  cmu_indic_fvtable,
  0  /* not freeable */
};
