/*****************************************************/
/**  Autogenerated Spam accent vectors for cmu_us_rms   */
/*****************************************************/
static const float cmu_us_rms_spamf0_accent_frame_0[] = { 
 0.177961, 0.116292, 0.176881, 0.143479, 0.185974, 0.082537, -0.146055, 0.788829, };
static const float cmu_us_rms_spamf0_accent_frame_1[] = { 
 0.181032, 0.117736, 0.181358, 0.147434, 0.185349, 0.093011, -0.501901, 0.644443, };
static const float cmu_us_rms_spamf0_accent_frame_2[] = { 
 0.133245, 0.087872, 0.120501, 0.094535, 0.168402, 0.077529, -0.243812, 0.781331, };
static const float cmu_us_rms_spamf0_accent_frame_3[] = { 
 0.206063, 0.113680, 0.240436, 0.163495, 0.227109, 0.095325, -0.257891, 0.582363, };
static const float cmu_us_rms_spamf0_accent_frame_4[] = { 
 0.183728, 0.092665, 0.213033, 0.132247, 0.218644, 0.086914, -0.108339, 0.589855, };
static const float cmu_us_rms_spamf0_accent_frame_5[] = { 
 0.181281, 0.094295, 0.178468, 0.120314, 0.178762, 0.096647, -0.701513, 0.470461, };
static const float cmu_us_rms_spamf0_accent_frame_6[] = { 
 0.140858, 0.098934, 0.131830, 0.108752, 0.169565, 0.106270, -0.599923, 0.661570, };
static const float cmu_us_rms_spamf0_accent_frame_7[] = { 
 0.197529, 0.112847, 0.203100, 0.137402, 0.203393, 0.116471, -0.601535, 0.573553, };
static const float cmu_us_rms_spamf0_accent_frame_8[] = { 
 0.215933, 0.106951, 0.233397, 0.157245, 0.217746, 0.097092, -0.212334, 0.756268, };
static const float cmu_us_rms_spamf0_accent_frame_9[] = { 
 0.218707, 0.134977, 0.252558, 0.185280, 0.219002, 0.106263, -0.428723, 0.565499, };
static const float cmu_us_rms_spamf0_accent_frame_10[] = { 
 0.229633, 0.121602, 0.259401, 0.162860, 0.238005, 0.094403, -0.272865, 0.591941, };
static const float cmu_us_rms_spamf0_accent_frame_11[] = { 
 0.214964, 0.105150, 0.266315, 0.164563, 0.231730, 0.084644, -0.108706, 0.562535, };
static const float cmu_us_rms_spamf0_accent_frame_12[] = { 
 0.195104, 0.106831, 0.194773, 0.124416, 0.209264, 0.081538, -0.102179, 0.729540, };
static const float cmu_us_rms_spamf0_accent_frame_13[] = { 
 0.254277, 0.132691, 0.300259, 0.191082, 0.247403, 0.086447, -0.031725, 0.631779, };
static const float cmu_us_rms_spamf0_accent_frame_14[] = { 
 0.241535, 0.104078, 0.253939, 0.140767, 0.244245, 0.082058, 0.120140, 0.711466, };
static const float cmu_us_rms_spamf0_accent_frame_15[] = { 
 0.216427, 0.097203, 0.207338, 0.114275, 0.217723, 0.085215, 0.081347, 0.794496, };
static const float cmu_us_rms_spamf0_accent_frame_16[] = { 
 0.193269, 0.099160, 0.185555, 0.120490, 0.204855, 0.063777, 0.487833, 0.585959, };
static const float cmu_us_rms_spamf0_accent_frame_17[] = { 
 0.228677, 0.111647, 0.255444, 0.166212, 0.242726, 0.059808, 0.407365, 0.505678, };
static const float cmu_us_rms_spamf0_accent_frame_18[] = { 
 0.238302, 0.114219, 0.253040, 0.159686, 0.231702, 0.077239, 0.201254, 0.674542, };
static const float cmu_us_rms_spamf0_accent_frame_19[] = { 
 0.191422, 0.111509, 0.182458, 0.127627, 0.213234, 0.109772, -0.294748, 0.755915, };
static const float cmu_us_rms_spamf0_accent_frame_20[] = { 
 0.232642, 0.110249, 0.240290, 0.140398, 0.232202, 0.109061, -0.230554, 0.745963, };
static const float cmu_us_rms_spamf0_accent_frame_21[] = { 
 0.125446, 0.088809, 0.114026, 0.088038, 0.159348, 0.076491, -0.283917, 0.808896, };
static const float cmu_us_rms_spamf0_accent_frame_22[] = { 
 0.178238, 0.112717, 0.186607, 0.138386, 0.206675, 0.080134, -0.067896, 0.703106, };
static const float cmu_us_rms_spamf0_accent_frame_23[] = { 
 0.126773, 0.072183, 0.127169, 0.088268, 0.177264, 0.068411, -0.049807, 0.696229, };
static const float cmu_us_rms_spamf0_accent_frame_24[] = { 
 0.201557, 0.101230, 0.207008, 0.127288, 0.221366, 0.101278, -0.091960, 0.720900, };
static const float cmu_us_rms_spamf0_accent_frame_25[] = { 
 0.195604, 0.104716, 0.203334, 0.124721, 0.210904, 0.096599, -0.321657, 0.690648, };
static const float cmu_us_rms_spamf0_accent_frame_26[] = { 
 0.211641, 0.113703, 0.217083, 0.135829, 0.215730, 0.089928, -0.366850, 0.689218, };
static const float cmu_us_rms_spamf0_accent_frame_27[] = { 
 0.229922, 0.116151, 0.226064, 0.121126, 0.237399, 0.100189, -0.643747, 0.502443, };
static const float cmu_us_rms_spamf0_accent_frame_28[] = { 
 0.220451, 0.114962, 0.241552, 0.143960, 0.238581, 0.087552, -0.161667, 0.646956, };
static const float cmu_us_rms_spamf0_accent_frame_29[] = { 
 0.258485, 0.123149, 0.276187, 0.151704, 0.255414, 0.100583, -0.364495, 0.623393, };
static const float cmu_us_rms_spamf0_accent_frame_30[] = { 
 0.239190, 0.121426, 0.259583, 0.154867, 0.239396, 0.097245, -0.146208, 0.703702, };
static const float cmu_us_rms_spamf0_accent_frame_31[] = { 
 0.227055, 0.088246, 0.254326, 0.131794, 0.250188, 0.087011, -0.019460, 0.640724, };
static const float cmu_us_rms_spamf0_accent_frame_32[] = { 
 0.194413, 0.108650, 0.184442, 0.111531, 0.202989, 0.101305, -0.387193, 0.757464, };
static const float cmu_us_rms_spamf0_accent_frame_33[] = { 
 0.224087, 0.119281, 0.221224, 0.133141, 0.221214, 0.108800, -0.620191, 0.561193, };
static const float cmu_us_rms_spamf0_accent_frame_34[] = { 
 0.208669, 0.113172, 0.220151, 0.145961, 0.224721, 0.094619, -0.368374, 0.644804, };
static const float cmu_us_rms_spamf0_accent_frame_35[] = { 
 0.246014, 0.119003, 0.267365, 0.146671, 0.248206, 0.099741, -0.459754, 0.523970, };
static const float cmu_us_rms_spamf0_accent_frame_36[] = { 
 0.256046, 0.114247, 0.273201, 0.142052, 0.260807, 0.109973, -0.358336, 0.609605, };
static const float cmu_us_rms_spamf0_accent_frame_37[] = { 
 0.227887, 0.114516, 0.228591, 0.124556, 0.226646, 0.093944, -0.616139, 0.466810, };
static const float cmu_us_rms_spamf0_accent_frame_38[] = { 
 0.231082, 0.119902, 0.247309, 0.149690, 0.242242, 0.105689, -0.483214, 0.542035, };
static const float cmu_us_rms_spamf0_accent_frame_39[] = { 
 0.136424, 0.096681, 0.129109, 0.110394, 0.157565, 0.086265, -0.651443, 0.599518, };
static const float cmu_us_rms_spamf0_accent_frame_40[] = { 
 0.196922, 0.098229, 0.183157, 0.102763, 0.197724, 0.114551, -0.779744, 0.481004, };
static const float cmu_us_rms_spamf0_accent_frame_41[] = { 
 0.263297, 0.108345, 0.246427, 0.116970, 0.239635, 0.122753, -0.727958, 0.546295, };
static const float cmu_us_rms_spamf0_accent_frame_42[] = { 
 0.237452, 0.106074, 0.215348, 0.118581, 0.216239, 0.114222, -0.591943, 0.711949, };
static const float cmu_us_rms_spamf0_accent_frame_43[] = { 
 0.194691, 0.084415, 0.172011, 0.081582, 0.204118, 0.094509, -0.649890, 0.611379, };
static const float cmu_us_rms_spamf0_accent_frame_44[] = { 
 0.226425, 0.111861, 0.241487, 0.149857, 0.205328, 0.092920, -0.386825, 0.692666, };
static const float cmu_us_rms_spamf0_accent_frame_45[] = { 
 0.222680, 0.105490, 0.246397, 0.133861, 0.221505, 0.110383, -0.603141, 0.436139, };
static const float cmu_us_rms_spamf0_accent_frame_46[] = { 
 0.235239, 0.098092, 0.261666, 0.143480, 0.229012, 0.105877, -0.454963, 0.572283, };
static const float cmu_us_rms_spamf0_accent_frame_47[] = { 
 0.289047, 0.105252, 0.321894, 0.177207, 0.266710, 0.122504, -0.590428, 0.449462, };
static const float cmu_us_rms_spamf0_accent_frame_48[] = { 
 0.264303, 0.101609, 0.292122, 0.143963, 0.251579, 0.115491, -0.499257, 0.523540, };
static const float cmu_us_rms_spamf0_accent_frame_49[] = { 
 0.237695, 0.106458, 0.232186, 0.140249, 0.219872, 0.116966, -0.670285, 0.565035, };
static const float cmu_us_rms_spamf0_accent_frame_50[] = { 
 0.257228, 0.107072, 0.285829, 0.161134, 0.228676, 0.100626, -0.442010, 0.596150, };
static const float cmu_us_rms_spamf0_accent_frame_51[] = { 
 0.322897, 0.096674, 0.344339, 0.164074, 0.277548, 0.118158, -0.475618, 0.637509, };
static const float cmu_us_rms_spamf0_accent_frame_52[] = { 
 0.319548, 0.108366, 0.324459, 0.149691, 0.265438, 0.123581, -0.645027, 0.550967, };
static const float cmu_us_rms_spamf0_accent_frame_53[] = { 
 0.335106, 0.111052, 0.360013, 0.167968, 0.265144, 0.110842, -0.574709, 0.522186, };
static const float cmu_us_rms_spamf0_accent_frame_54[] = { 
 0.362739, 0.097685, 0.398012, 0.152907, 0.313855, 0.117359, -0.520042, 0.512701, };
static const float cmu_us_rms_spamf0_accent_frame_55[] = { 
 0.408515, 0.112997, 0.484170, 0.228386, 0.352117, 0.114630, -0.496918, 0.434265, };
static const float cmu_us_rms_spamf0_accent_frame_56[] = { 
 0.440444, 0.122461, 0.540817, 0.242898, 0.363210, 0.104812, -0.487146, 0.463921, };
static const float cmu_us_rms_spamf0_accent_frame_57[] = { 
 0.425144, 0.127413, 0.522285, 0.239852, 0.349576, 0.122176, -0.558007, 0.329128, };
static const float cmu_us_rms_spamf0_accent_frame_58[] = { 
 0.495012, 0.110829, 0.674753, 0.260042, 0.405949, 0.092430, -0.459573, 0.297642, };
static const float cmu_us_rms_spamf0_accent_frame_59[] = { 
 0.270265, 0.106518, 0.333028, 0.179286, 0.258725, 0.077477, -0.082828, 0.597581, };
static const float cmu_us_rms_spamf0_accent_frame_60[] = { 
 0.294698, 0.125424, 0.400296, 0.215610, 0.286180, 0.097672, -0.165649, 0.451096, };
static const float cmu_us_rms_spamf0_accent_frame_61[] = { 
 0.305142, 0.123442, 0.347007, 0.189021, 0.287508, 0.096064, -0.147283, 0.673479, };
static const float cmu_us_rms_spamf0_accent_frame_62[] = { 
 0.313580, 0.119507, 0.369188, 0.200385, 0.273272, 0.106166, -0.281834, 0.650343, };
static const float cmu_us_rms_spamf0_accent_frame_63[] = { 
 0.292145, 0.101181, 0.331724, 0.169641, 0.264340, 0.090872, -0.086841, 0.681287, };
static const float cmu_us_rms_spamf0_accent_frame_64[] = { 
 0.258008, 0.113812, 0.291043, 0.160745, 0.272028, 0.101023, -0.204783, 0.659224, };
static const float cmu_us_rms_spamf0_accent_frame_65[] = { 
 0.326742, 0.098615, 0.381485, 0.165252, 0.284173, 0.081831, 0.059242, 0.646961, };
static const float cmu_us_rms_spamf0_accent_frame_66[] = { 
 0.251086, 0.114731, 0.261944, 0.128554, 0.266532, 0.098899, -0.440059, 0.608688, };
static const float cmu_us_rms_spamf0_accent_frame_67[] = { 
 0.286944, 0.128309, 0.318344, 0.154463, 0.278909, 0.111022, -0.375441, 0.572744, };
static const float cmu_us_rms_spamf0_accent_frame_68[] = { 
 0.277208, 0.120873, 0.292130, 0.159486, 0.263249, 0.095516, -0.135595, 0.740686, };
static const float cmu_us_rms_spamf0_accent_frame_69[] = { 
 0.333871, 0.117578, 0.409739, 0.204404, 0.313308, 0.119107, -0.400669, 0.463206, };
static const float cmu_us_rms_spamf0_accent_frame_70[] = { 
 0.358829, 0.126053, 0.469010, 0.231496, 0.335408, 0.101885, -0.105802, 0.549863, };
static const float cmu_us_rms_spamf0_accent_frame_71[] = { 
 0.300511, 0.124826, 0.383412, 0.199966, 0.290252, 0.097146, -0.116087, 0.543791, };
static const float cmu_us_rms_spamf0_accent_frame_72[] = { 
 0.281094, 0.103926, 0.333127, 0.179425, 0.270844, 0.062558, 0.383337, 0.461168, };
static const float cmu_us_rms_spamf0_accent_frame_73[] = { 
 0.265872, 0.111033, 0.336790, 0.184314, 0.270669, 0.074701, 0.153106, 0.497328, };
static const float cmu_us_rms_spamf0_accent_frame_74[] = { 
 0.299534, 0.115710, 0.389867, 0.207616, 0.278148, 0.077607, 0.132954, 0.487909, };
static const float cmu_us_rms_spamf0_accent_frame_75[] = { 
 0.263374, 0.106198, 0.293570, 0.150797, 0.261945, 0.087126, 0.029750, 0.659928, };
static const float cmu_us_rms_spamf0_accent_frame_76[] = { 
 0.281421, 0.115823, 0.342194, 0.180589, 0.273589, 0.082137, 0.127084, 0.552961, };
static const float cmu_us_rms_spamf0_accent_frame_77[] = { 
 0.312879, 0.117601, 0.387670, 0.200365, 0.287593, 0.086807, 0.009192, 0.596336, };
static const float cmu_us_rms_spamf0_accent_frame_78[] = { 
 0.328141, 0.118709, 0.433790, 0.223369, 0.299105, 0.095458, -0.075016, 0.510490, };
static const float cmu_us_rms_spamf0_accent_frame_79[] = { 
 0.380091, 0.130996, 0.524887, 0.243448, 0.349810, 0.099497, -0.204724, 0.454117, };
static const float cmu_us_rms_spamf0_accent_frame_80[] = { 
 0.235761, 0.106311, 0.225851, 0.113451, 0.238071, 0.106669, -0.456721, 0.737039, };
static const float cmu_us_rms_spamf0_accent_frame_81[] = { 
 0.250744, 0.107485, 0.232790, 0.110795, 0.231248, 0.123747, -0.692871, 0.607681, };
static const float cmu_us_rms_spamf0_accent_frame_82[] = { 
 0.215962, 0.102319, 0.191893, 0.107114, 0.223293, 0.099870, -0.450069, 0.748445, };
static const float cmu_us_rms_spamf0_accent_frame_83[] = { 
 0.262607, 0.118649, 0.251559, 0.119293, 0.272782, 0.106028, -0.418888, 0.733274, };
static const float cmu_us_rms_spamf0_accent_frame_84[] = { 
 0.286612, 0.126304, 0.270635, 0.125772, 0.260418, 0.116491, -0.537975, 0.689598, };
static const float cmu_us_rms_spamf0_accent_frame_85[] = { 
 0.262601, 0.117373, 0.342634, 0.201676, 0.273610, 0.083932, -0.020036, 0.508338, };
static const float cmu_us_rms_spamf0_accent_frame_86[] = { 
 0.288613, 0.102791, 0.362801, 0.185072, 0.271482, 0.063012, 0.263726, 0.453503, };
static const float cmu_us_rms_spamf0_accent_frame_87[] = { 
 0.317935, 0.121501, 0.431880, 0.218843, 0.296007, 0.098330, -0.074140, 0.468173, };
static const float cmu_us_rms_spamf0_accent_frame_88[] = { 
 0.266285, 0.132855, 0.333010, 0.212123, 0.256567, 0.109739, -0.220778, 0.567162, };
static const float cmu_us_rms_spamf0_accent_frame_89[] = { 
 0.293099, 0.109824, 0.318220, 0.160838, 0.265722, 0.126469, -0.590721, 0.504864, };
static const float cmu_us_rms_spamf0_accent_frame_90[] = { 
 0.247148, 0.105607, 0.277137, 0.158541, 0.239947, 0.116075, -0.529241, 0.532452, };
static const float cmu_us_rms_spamf0_accent_frame_91[] = { 
 0.263968, 0.106299, 0.283632, 0.163275, 0.249938, 0.115114, -0.496826, 0.585119, };
static const float cmu_us_rms_spamf0_accent_frame_92[] = { 
 0.283888, 0.120144, 0.323435, 0.176269, 0.263920, 0.114766, -0.502298, 0.555097, };
static const float cmu_us_rms_spamf0_accent_frame_93[] = { 
 0.290322, 0.120559, 0.320697, 0.199774, 0.274347, 0.120480, -0.307909, 0.706877, };


const float * const cmu_us_rms_spamf0_accent_vectors[] = {
   cmu_us_rms_spamf0_accent_frame_0,
   cmu_us_rms_spamf0_accent_frame_1,
   cmu_us_rms_spamf0_accent_frame_2,
   cmu_us_rms_spamf0_accent_frame_3,
   cmu_us_rms_spamf0_accent_frame_4,
   cmu_us_rms_spamf0_accent_frame_5,
   cmu_us_rms_spamf0_accent_frame_6,
   cmu_us_rms_spamf0_accent_frame_7,
   cmu_us_rms_spamf0_accent_frame_8,
   cmu_us_rms_spamf0_accent_frame_9,
   cmu_us_rms_spamf0_accent_frame_10,
   cmu_us_rms_spamf0_accent_frame_11,
   cmu_us_rms_spamf0_accent_frame_12,
   cmu_us_rms_spamf0_accent_frame_13,
   cmu_us_rms_spamf0_accent_frame_14,
   cmu_us_rms_spamf0_accent_frame_15,
   cmu_us_rms_spamf0_accent_frame_16,
   cmu_us_rms_spamf0_accent_frame_17,
   cmu_us_rms_spamf0_accent_frame_18,
   cmu_us_rms_spamf0_accent_frame_19,
   cmu_us_rms_spamf0_accent_frame_20,
   cmu_us_rms_spamf0_accent_frame_21,
   cmu_us_rms_spamf0_accent_frame_22,
   cmu_us_rms_spamf0_accent_frame_23,
   cmu_us_rms_spamf0_accent_frame_24,
   cmu_us_rms_spamf0_accent_frame_25,
   cmu_us_rms_spamf0_accent_frame_26,
   cmu_us_rms_spamf0_accent_frame_27,
   cmu_us_rms_spamf0_accent_frame_28,
   cmu_us_rms_spamf0_accent_frame_29,
   cmu_us_rms_spamf0_accent_frame_30,
   cmu_us_rms_spamf0_accent_frame_31,
   cmu_us_rms_spamf0_accent_frame_32,
   cmu_us_rms_spamf0_accent_frame_33,
   cmu_us_rms_spamf0_accent_frame_34,
   cmu_us_rms_spamf0_accent_frame_35,
   cmu_us_rms_spamf0_accent_frame_36,
   cmu_us_rms_spamf0_accent_frame_37,
   cmu_us_rms_spamf0_accent_frame_38,
   cmu_us_rms_spamf0_accent_frame_39,
   cmu_us_rms_spamf0_accent_frame_40,
   cmu_us_rms_spamf0_accent_frame_41,
   cmu_us_rms_spamf0_accent_frame_42,
   cmu_us_rms_spamf0_accent_frame_43,
   cmu_us_rms_spamf0_accent_frame_44,
   cmu_us_rms_spamf0_accent_frame_45,
   cmu_us_rms_spamf0_accent_frame_46,
   cmu_us_rms_spamf0_accent_frame_47,
   cmu_us_rms_spamf0_accent_frame_48,
   cmu_us_rms_spamf0_accent_frame_49,
   cmu_us_rms_spamf0_accent_frame_50,
   cmu_us_rms_spamf0_accent_frame_51,
   cmu_us_rms_spamf0_accent_frame_52,
   cmu_us_rms_spamf0_accent_frame_53,
   cmu_us_rms_spamf0_accent_frame_54,
   cmu_us_rms_spamf0_accent_frame_55,
   cmu_us_rms_spamf0_accent_frame_56,
   cmu_us_rms_spamf0_accent_frame_57,
   cmu_us_rms_spamf0_accent_frame_58,
   cmu_us_rms_spamf0_accent_frame_59,
   cmu_us_rms_spamf0_accent_frame_60,
   cmu_us_rms_spamf0_accent_frame_61,
   cmu_us_rms_spamf0_accent_frame_62,
   cmu_us_rms_spamf0_accent_frame_63,
   cmu_us_rms_spamf0_accent_frame_64,
   cmu_us_rms_spamf0_accent_frame_65,
   cmu_us_rms_spamf0_accent_frame_66,
   cmu_us_rms_spamf0_accent_frame_67,
   cmu_us_rms_spamf0_accent_frame_68,
   cmu_us_rms_spamf0_accent_frame_69,
   cmu_us_rms_spamf0_accent_frame_70,
   cmu_us_rms_spamf0_accent_frame_71,
   cmu_us_rms_spamf0_accent_frame_72,
   cmu_us_rms_spamf0_accent_frame_73,
   cmu_us_rms_spamf0_accent_frame_74,
   cmu_us_rms_spamf0_accent_frame_75,
   cmu_us_rms_spamf0_accent_frame_76,
   cmu_us_rms_spamf0_accent_frame_77,
   cmu_us_rms_spamf0_accent_frame_78,
   cmu_us_rms_spamf0_accent_frame_79,
   cmu_us_rms_spamf0_accent_frame_80,
   cmu_us_rms_spamf0_accent_frame_81,
   cmu_us_rms_spamf0_accent_frame_82,
   cmu_us_rms_spamf0_accent_frame_83,
   cmu_us_rms_spamf0_accent_frame_84,
   cmu_us_rms_spamf0_accent_frame_85,
   cmu_us_rms_spamf0_accent_frame_86,
   cmu_us_rms_spamf0_accent_frame_87,
   cmu_us_rms_spamf0_accent_frame_88,
   cmu_us_rms_spamf0_accent_frame_89,
   cmu_us_rms_spamf0_accent_frame_90,
   cmu_us_rms_spamf0_accent_frame_91,
   cmu_us_rms_spamf0_accent_frame_92,
   cmu_us_rms_spamf0_accent_frame_93,
};

