/*******************************************************/
/**  Autogenerated phoneset trees for cmu_grapheme    */
/*******************************************************/

#include "cst_string.h"
#include "cst_phoneset.h"
extern const cst_phoneset cmu_grapheme_phoneset;


static const char * const cmu_grapheme_featnames[] = {
 "clst",
 "vc",
 "vlng",
 "vheight",
 "vfront",
 "vrnd",
 "ctype",
 "cplace",
 "cvox",
 "asp",
 "nuk",
 NULL };

static const char * const cmu_grapheme_phonenames[] = {
 "pau",
 "QQ",
 "QM",
 "A",
 "a:",
 ">",
 "tra",
 "t:ra",
 "h:",
 ">:",
 "A:",
 "i",
 "i:",
 "u",
 "u:",
 "9r=",
 "9r:",
 "rr=",
 "rr",
 "r",
 "rrh",
 "l=",
 "@",
 "@:",
 "e:",
 "aI",
 ">I",
 "o:",
 "aU",
 "oU",
 "oI",
 "q",
 "k",
 "kh",
 "G",
 "g",
 "gh",
 "x",
 "N",
 "c",
 "ch",
 "z",
 "z~",
 "J",
 "Jh",
 "n~",
 "T",
 "tB",
 "tBh",
 "D",
 "d",
 "d~",
 "dB",
 "dBh",
 "n",
 "nX",
 "nB",
 "tr",
 "tR",
 "dr",
 "dR",
 "nr",
 "p",
 "P",
 "ph",
 "f",
 "b",
 "bh",
 "m",
 "M",
 "j",
 "9rB",
 "9r",
 "l",
 "lr",
 "lr=",
 "V",
 "v",
 "c}",
 "S",
 "sr",
 "s",
 "h",
 "s~",
 "t",
 "t~",
 "hv",
 "H",
 "n:",
 "E",
 "e",
 "o",
 "6",
 "6j",
 "6w",
 "9:",
 "9y",
 "E:",
 "O:",
 "O:j",
 "a:j",
 "a:w",
 "dz",
 "dZ",
 "Z",
 "ej",
 "gw",
 "iw",
 "kw",
 "ow",
 "ts",
 "tS",
 "u:j",
 "w",
 "y:",
 "LB",
 NULL };

static const int cmu_grapheme_fv_000[] = { 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,   -1 };
static const int cmu_grapheme_fv_001[] = { 0, 0, 1, 1, 1, 1, 2, 3, 0, 0, 0,   -1 };
static const int cmu_grapheme_fv_002[] = { 0, 0, 1, 1, 1, 1, 2, 4, 0, 0, 0,   -1 };
static const int cmu_grapheme_fv_003[] = { 0, 5, 2, 6, 6, 0, 1, 1, 1, 0, 1,   -1 };
static const int cmu_grapheme_fv_004[] = { 0, 5, 7, 6, 6, 0, 1, 1, 1, 0, 1,   -1 };
static const int cmu_grapheme_fv_005[] = { 0, 5, 2, 6, 6, 0, 1, 1, 1, 0, 1,   -1 };
static const int cmu_grapheme_fv_006[] = { 5, 5, 2, 6, 6, 0, 2, 8, 5, 0, 1,   -1 };
static const int cmu_grapheme_fv_007[] = { 5, 5, 2, 6, 6, 0, 2, 9, 5, 0, 1,   -1 };
static const int cmu_grapheme_fv_008[] = { 0, 5, 2, 6, 6, 0, 10, 1, 0, 5, 1,   -1 };
static const int cmu_grapheme_fv_009[] = { 0, 5, 7, 11, 6, 0, 1, 1, 1, 0, 1,   -1 };
static const int cmu_grapheme_fv_010[] = { 0, 5, 7, 11, 6, 0, 1, 1, 1, 0, 1,   -1 };
static const int cmu_grapheme_fv_011[] = { 0, 5, 2, 12, 12, 0, 1, 1, 1, 0, 1,   -1 };
static const int cmu_grapheme_fv_012[] = { 0, 5, 7, 12, 12, 0, 1, 1, 1, 0, 1,   -1 };
static const int cmu_grapheme_fv_013[] = { 0, 5, 2, 12, 11, 5, 1, 1, 1, 0, 1,   -1 };
static const int cmu_grapheme_fv_014[] = { 0, 5, 7, 12, 11, 5, 1, 1, 1, 0, 1,   -1 };
static const int cmu_grapheme_fv_015[] = { 0, 5, 2, 12, 11, 5, 1, 1, 1, 0, 1,   -1 };
static const int cmu_grapheme_fv_016[] = { 0, 5, 2, 12, 11, 5, 1, 1, 1, 0, 1,   -1 };
static const int cmu_grapheme_fv_017[] = { 0, 5, 7, 12, 11, 5, 1, 1, 1, 0, 1,   -1 };
static const int cmu_grapheme_fv_018[] = { 0, 5, 7, 12, 11, 5, 1, 1, 1, 0, 1,   -1 };
static const int cmu_grapheme_fv_019[] = { 0, 0, 1, 1, 1, 5, 7, 13, 5, 0, 0,   -1 };
static const int cmu_grapheme_fv_020[] = { 0, 5, 7, 12, 11, 5, 1, 1, 1, 0, 1,   -1 };
static const int cmu_grapheme_fv_021[] = { 0, 5, 2, 12, 11, 5, 1, 1, 1, 0, 1,   -1 };
static const int cmu_grapheme_fv_022[] = { 0, 5, 2, 6, 12, 0, 1, 1, 1, 0, 1,   -1 };
static const int cmu_grapheme_fv_023[] = { 0, 5, 7, 6, 12, 0, 1, 1, 1, 0, 1,   -1 };
static const int cmu_grapheme_fv_024[] = { 0, 5, 7, 6, 12, 0, 1, 1, 1, 0, 1,   -1 };
static const int cmu_grapheme_fv_025[] = { 0, 5, 8, 6, 12, 0, 1, 1, 1, 0, 1,   -1 };
static const int cmu_grapheme_fv_026[] = { 0, 5, 8, 6, 12, 0, 1, 1, 1, 0, 1,   -1 };
static const int cmu_grapheme_fv_027[] = { 0, 5, 7, 6, 11, 5, 1, 1, 1, 0, 1,   -1 };
static const int cmu_grapheme_fv_028[] = { 0, 5, 8, 12, 11, 5, 1, 1, 1, 0, 1,   -1 };
static const int cmu_grapheme_fv_029[] = { 0, 5, 8, 12, 11, 5, 1, 1, 1, 0, 1,   -1 };
static const int cmu_grapheme_fv_030[] = { 0, 5, 8, 12, 11, 5, 1, 1, 1, 0, 1,   -1 };
static const int cmu_grapheme_fv_031[] = { 0, 0, 1, 1, 1, 1, 2, 4, 0, 0, 0,   -1 };
static const int cmu_grapheme_fv_032[] = { 0, 0, 1, 1, 1, 1, 2, 4, 0, 0, 0,   -1 };
static const int cmu_grapheme_fv_033[] = { 0, 0, 1, 1, 1, 1, 2, 4, 0, 5, 0,   -1 };
static const int cmu_grapheme_fv_034[] = { 0, 0, 1, 1, 1, 1, 2, 4, 5, 0, 0,   -1 };
static const int cmu_grapheme_fv_035[] = { 0, 0, 1, 1, 1, 1, 2, 4, 5, 0, 0,   -1 };
static const int cmu_grapheme_fv_036[] = { 0, 0, 1, 1, 1, 1, 2, 4, 5, 5, 0,   -1 };
static const int cmu_grapheme_fv_037[] = { 0, 0, 1, 1, 1, 1, 2, 4, 5, 5, 0,   -1 };
static const int cmu_grapheme_fv_038[] = { 0, 0, 1, 1, 1, 1, 14, 4, 5, 0, 0,   -1 };
static const int cmu_grapheme_fv_039[] = { 0, 0, 1, 1, 1, 1, 13, 15, 0, 0, 0,   -1 };
static const int cmu_grapheme_fv_040[] = { 0, 0, 1, 1, 1, 1, 13, 15, 0, 5, 0,   -1 };
static const int cmu_grapheme_fv_041[] = { 0, 0, 1, 1, 1, 1, 13, 15, 5, 0, 0,   -1 };
static const int cmu_grapheme_fv_042[] = { 0, 0, 1, 1, 1, 1, 13, 15, 5, 0, 0,   -1 };
static const int cmu_grapheme_fv_043[] = { 0, 0, 1, 1, 1, 1, 13, 15, 5, 0, 0,   -1 };
static const int cmu_grapheme_fv_044[] = { 0, 0, 1, 1, 1, 1, 13, 15, 5, 5, 0,   -1 };
static const int cmu_grapheme_fv_045[] = { 0, 0, 1, 1, 1, 1, 14, 15, 5, 0, 0,   -1 };
static const int cmu_grapheme_fv_046[] = { 0, 0, 1, 1, 1, 1, 10, 8, 0, 0, 0,   -1 };
static const int cmu_grapheme_fv_047[] = { 0, 0, 1, 1, 1, 1, 2, 8, 0, 0, 0,   -1 };
static const int cmu_grapheme_fv_048[] = { 0, 0, 1, 1, 1, 1, 2, 8, 0, 5, 0,   -1 };
static const int cmu_grapheme_fv_049[] = { 0, 0, 1, 1, 1, 1, 2, 8, 5, 0, 0,   -1 };
static const int cmu_grapheme_fv_050[] = { 0, 0, 1, 1, 1, 1, 2, 8, 5, 0, 0,   -1 };
static const int cmu_grapheme_fv_051[] = { 0, 0, 1, 1, 1, 1, 2, 8, 5, 0, 0,   -1 };
static const int cmu_grapheme_fv_052[] = { 0, 0, 1, 1, 1, 1, 2, 8, 5, 0, 0,   -1 };
static const int cmu_grapheme_fv_053[] = { 0, 0, 1, 1, 1, 1, 2, 8, 5, 5, 0,   -1 };
static const int cmu_grapheme_fv_054[] = { 0, 0, 1, 1, 1, 1, 14, 8, 5, 0, 0,   -1 };
static const int cmu_grapheme_fv_055[] = { 0, 0, 1, 1, 1, 1, 14, 8, 5, 0, 0,   -1 };
static const int cmu_grapheme_fv_056[] = { 0, 0, 1, 1, 1, 1, 14, 8, 5, 0, 0,   -1 };
static const int cmu_grapheme_fv_057[] = { 0, 0, 1, 1, 1, 1, 2, 13, 0, 0, 0,   -1 };
static const int cmu_grapheme_fv_058[] = { 0, 0, 1, 1, 1, 1, 2, 13, 0, 5, 0,   -1 };
static const int cmu_grapheme_fv_059[] = { 0, 0, 1, 1, 1, 1, 2, 13, 5, 0, 0,   -1 };
static const int cmu_grapheme_fv_060[] = { 0, 0, 1, 1, 1, 1, 2, 13, 5, 5, 0,   -1 };
static const int cmu_grapheme_fv_061[] = { 0, 0, 1, 1, 1, 1, 14, 13, 5, 0, 0,   -1 };
static const int cmu_grapheme_fv_062[] = { 0, 0, 1, 1, 1, 1, 2, 7, 0, 0, 0,   -1 };
static const int cmu_grapheme_fv_063[] = { 0, 0, 1, 1, 1, 1, 2, 7, 0, 0, 0,   -1 };
static const int cmu_grapheme_fv_064[] = { 0, 0, 1, 1, 1, 1, 2, 7, 0, 5, 0,   -1 };
static const int cmu_grapheme_fv_065[] = { 0, 0, 1, 1, 1, 1, 2, 7, 0, 5, 0,   -1 };
static const int cmu_grapheme_fv_066[] = { 0, 0, 1, 1, 1, 1, 2, 7, 5, 0, 0,   -1 };
static const int cmu_grapheme_fv_067[] = { 0, 0, 1, 1, 1, 1, 2, 7, 5, 5, 0,   -1 };
static const int cmu_grapheme_fv_068[] = { 0, 0, 1, 1, 1, 1, 14, 7, 5, 0, 0,   -1 };
static const int cmu_grapheme_fv_069[] = { 0, 0, 1, 1, 1, 1, 14, 7, 5, 0, 0,   -1 };
static const int cmu_grapheme_fv_070[] = { 0, 0, 1, 1, 1, 1, 7, 4, 5, 0, 0,   -1 };
static const int cmu_grapheme_fv_071[] = { 0, 0, 1, 1, 1, 1, 7, 15, 5, 0, 0,   -1 };
static const int cmu_grapheme_fv_072[] = { 0, 0, 1, 1, 1, 1, 7, 15, 5, 0, 0,   -1 };
static const int cmu_grapheme_fv_073[] = { 0, 0, 1, 1, 1, 1, 7, 8, 5, 0, 0,   -1 };
static const int cmu_grapheme_fv_074[] = { 0, 0, 1, 1, 1, 1, 7, 15, 5, 0, 0,   -1 };
static const int cmu_grapheme_fv_075[] = { 0, 0, 1, 1, 1, 1, 7, 15, 5, 0, 0,   -1 };
static const int cmu_grapheme_fv_076[] = { 0, 0, 1, 1, 1, 1, 7, 8, 5, 0, 0,   -1 };
static const int cmu_grapheme_fv_077[] = { 0, 0, 1, 1, 1, 1, 7, 8, 5, 0, 0,   -1 };
static const int cmu_grapheme_fv_078[] = { 0, 0, 1, 1, 1, 1, 10, 4, 0, 5, 0,   -1 };
static const int cmu_grapheme_fv_079[] = { 0, 0, 1, 1, 1, 1, 10, 15, 5, 5, 0,   -1 };
static const int cmu_grapheme_fv_080[] = { 0, 0, 1, 1, 1, 1, 10, 15, 5, 5, 0,   -1 };
static const int cmu_grapheme_fv_081[] = { 0, 0, 1, 1, 1, 1, 10, 8, 0, 0, 0,   -1 };
static const int cmu_grapheme_fv_082[] = { 0, 0, 1, 1, 1, 1, 10, 4, 0, 5, 0,   -1 };
static const int cmu_grapheme_fv_083[] = { 0, 0, 1, 1, 1, 1, 10, 8, 0, 0, 0,   -1 };
static const int cmu_grapheme_fv_084[] = { 0, 0, 1, 1, 1, 1, 2, 13, 0, 0, 0,   -1 };
static const int cmu_grapheme_fv_085[] = { 0, 0, 1, 1, 1, 1, 2, 13, 0, 0, 0,   -1 };
static const int cmu_grapheme_fv_086[] = { 0, 0, 1, 1, 1, 1, 10, 4, 0, 5, 0,   -1 };
static const int cmu_grapheme_fv_087[] = { 0, 0, 1, 1, 1, 1, 7, 15, 5, 0, 0,   -1 };
static const int cmu_grapheme_fv_088[] = { 0, 0, 1, 1, 1, 1, 14, 8, 5, 0, 0,   -1 };
static const int cmu_grapheme_fv_089[] = { 0, 5, 2, 6, 12, 0, 1, 1, 1, 0, 0,   -1 };
static const int cmu_grapheme_fv_090[] = { 0, 5, 2, 6, 12, 0, 1, 1, 1, 0, 0,   -1 };
static const int cmu_grapheme_fv_091[] = { 0, 5, 2, 6, 11, 5, 1, 1, 1, 0, 0,   -1 };
static const int cmu_grapheme_fv_092[] = { 0, 5, 1, 1, 1, 0, 1, 1, 1, 0, 1,   -1 };
static const int cmu_grapheme_fv_093[] = { 0, 5, 1, 1, 1, 0, 16, 7, 1, 0, 1,   -1 };
static const int cmu_grapheme_fv_094[] = { 0, 5, 1, 1, 1, 5, 16, 15, 1, 0, 1,   -1 };
static const int cmu_grapheme_fv_095[] = { 0, 5, 7, 1, 1, 0, 1, 1, 1, 0, 1,   -1 };
static const int cmu_grapheme_fv_096[] = { 0, 5, 1, 1, 1, 0, 16, 7, 1, 0, 1,   -1 };
static const int cmu_grapheme_fv_097[] = { 0, 5, 7, 6, 12, 0, 1, 1, 1, 0, 0,   -1 };
static const int cmu_grapheme_fv_098[] = { 0, 5, 7, 6, 11, 0, 1, 1, 1, 0, 0,   -1 };
static const int cmu_grapheme_fv_099[] = { 0, 5, 7, 6, 11, 0, 16, 7, 5, 0, 0,   -1 };
static const int cmu_grapheme_fv_100[] = { 0, 5, 7, 11, 12, 0, 16, 7, 5, 0, 0,   -1 };
static const int cmu_grapheme_fv_101[] = { 0, 5, 7, 11, 12, 0, 16, 7, 5, 0, 0,   -1 };
static const int cmu_grapheme_fv_102[] = { 0, 0, 1, 1, 1, 1, 13, 15, 5, 0, 0,   -1 };
static const int cmu_grapheme_fv_103[] = { 0, 0, 1, 1, 1, 1, 13, 15, 5, 0, 0,   -1 };
static const int cmu_grapheme_fv_104[] = { 0, 0, 1, 1, 1, 1, 13, 15, 5, 0, 0,   -1 };
static const int cmu_grapheme_fv_105[] = { 0, 5, 2, 6, 12, 0, 16, 15, 1, 0, 0,   -1 };
static const int cmu_grapheme_fv_106[] = { 0, 0, 1, 1, 1, 1, 2, 7, 5, 0, 0,   -1 };
static const int cmu_grapheme_fv_107[] = { 0, 5, 2, 12, 12, 0, 16, 7, 1, 0, 0,   -1 };
static const int cmu_grapheme_fv_108[] = { 0, 0, 1, 1, 1, 1, 2, 7, 0, 0, 0,   -1 };
static const int cmu_grapheme_fv_109[] = { 0, 5, 2, 6, 11, 0, 16, 7, 1, 0, 0,   -1 };
static const int cmu_grapheme_fv_110[] = { 0, 0, 1, 1, 1, 1, 2, 13, 0, 0, 0,   -1 };
static const int cmu_grapheme_fv_111[] = { 0, 0, 1, 1, 1, 1, 2, 13, 0, 0, 0,   -1 };
static const int cmu_grapheme_fv_112[] = { 0, 5, 7, 12, 11, 5, 16, 15, 1, 0, 0,   -1 };
static const int cmu_grapheme_fv_113[] = { 0, 0, 1, 1, 1, 5, 16, 7, 5, 0, 0,   -1 };
static const int cmu_grapheme_fv_114[] = { 0, 0, 7, 1, 1, 0, 16, 15, 5, 0, 0,   -1 };
static const int cmu_grapheme_fv_115[] = { 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,   -1 };
static const int cmu_grapheme_fv_116[] = { 0 };

static const int * const cmu_grapheme_fvtable[] = {
  cmu_grapheme_fv_000, 
  cmu_grapheme_fv_001, 
  cmu_grapheme_fv_002, 
  cmu_grapheme_fv_003, 
  cmu_grapheme_fv_004, 
  cmu_grapheme_fv_005, 
  cmu_grapheme_fv_006, 
  cmu_grapheme_fv_007, 
  cmu_grapheme_fv_008, 
  cmu_grapheme_fv_009, 
  cmu_grapheme_fv_010, 
  cmu_grapheme_fv_011, 
  cmu_grapheme_fv_012, 
  cmu_grapheme_fv_013, 
  cmu_grapheme_fv_014, 
  cmu_grapheme_fv_015, 
  cmu_grapheme_fv_016, 
  cmu_grapheme_fv_017, 
  cmu_grapheme_fv_018, 
  cmu_grapheme_fv_019, 
  cmu_grapheme_fv_020, 
  cmu_grapheme_fv_021, 
  cmu_grapheme_fv_022, 
  cmu_grapheme_fv_023, 
  cmu_grapheme_fv_024, 
  cmu_grapheme_fv_025, 
  cmu_grapheme_fv_026, 
  cmu_grapheme_fv_027, 
  cmu_grapheme_fv_028, 
  cmu_grapheme_fv_029, 
  cmu_grapheme_fv_030, 
  cmu_grapheme_fv_031, 
  cmu_grapheme_fv_032, 
  cmu_grapheme_fv_033, 
  cmu_grapheme_fv_034, 
  cmu_grapheme_fv_035, 
  cmu_grapheme_fv_036, 
  cmu_grapheme_fv_037, 
  cmu_grapheme_fv_038, 
  cmu_grapheme_fv_039, 
  cmu_grapheme_fv_040, 
  cmu_grapheme_fv_041, 
  cmu_grapheme_fv_042, 
  cmu_grapheme_fv_043, 
  cmu_grapheme_fv_044, 
  cmu_grapheme_fv_045, 
  cmu_grapheme_fv_046, 
  cmu_grapheme_fv_047, 
  cmu_grapheme_fv_048, 
  cmu_grapheme_fv_049, 
  cmu_grapheme_fv_050, 
  cmu_grapheme_fv_051, 
  cmu_grapheme_fv_052, 
  cmu_grapheme_fv_053, 
  cmu_grapheme_fv_054, 
  cmu_grapheme_fv_055, 
  cmu_grapheme_fv_056, 
  cmu_grapheme_fv_057, 
  cmu_grapheme_fv_058, 
  cmu_grapheme_fv_059, 
  cmu_grapheme_fv_060, 
  cmu_grapheme_fv_061, 
  cmu_grapheme_fv_062, 
  cmu_grapheme_fv_063, 
  cmu_grapheme_fv_064, 
  cmu_grapheme_fv_065, 
  cmu_grapheme_fv_066, 
  cmu_grapheme_fv_067, 
  cmu_grapheme_fv_068, 
  cmu_grapheme_fv_069, 
  cmu_grapheme_fv_070, 
  cmu_grapheme_fv_071, 
  cmu_grapheme_fv_072, 
  cmu_grapheme_fv_073, 
  cmu_grapheme_fv_074, 
  cmu_grapheme_fv_075, 
  cmu_grapheme_fv_076, 
  cmu_grapheme_fv_077, 
  cmu_grapheme_fv_078, 
  cmu_grapheme_fv_079, 
  cmu_grapheme_fv_080, 
  cmu_grapheme_fv_081, 
  cmu_grapheme_fv_082, 
  cmu_grapheme_fv_083, 
  cmu_grapheme_fv_084, 
  cmu_grapheme_fv_085, 
  cmu_grapheme_fv_086, 
  cmu_grapheme_fv_087, 
  cmu_grapheme_fv_088, 
  cmu_grapheme_fv_089, 
  cmu_grapheme_fv_090, 
  cmu_grapheme_fv_091, 
  cmu_grapheme_fv_092, 
  cmu_grapheme_fv_093, 
  cmu_grapheme_fv_094, 
  cmu_grapheme_fv_095, 
  cmu_grapheme_fv_096, 
  cmu_grapheme_fv_097, 
  cmu_grapheme_fv_098, 
  cmu_grapheme_fv_099, 
  cmu_grapheme_fv_100, 
  cmu_grapheme_fv_101, 
  cmu_grapheme_fv_102, 
  cmu_grapheme_fv_103, 
  cmu_grapheme_fv_104, 
  cmu_grapheme_fv_105, 
  cmu_grapheme_fv_106, 
  cmu_grapheme_fv_107, 
  cmu_grapheme_fv_108, 
  cmu_grapheme_fv_109, 
  cmu_grapheme_fv_110, 
  cmu_grapheme_fv_111, 
  cmu_grapheme_fv_112, 
  cmu_grapheme_fv_113, 
  cmu_grapheme_fv_114, 
  cmu_grapheme_fv_115, 
 cmu_grapheme_fv_116 };

DEF_STATIC_CONST_VAL_STRING(featval_0,"-");
DEF_STATIC_CONST_VAL_STRING(featval_1,"0");
DEF_STATIC_CONST_VAL_STRING(featval_2,"s");
DEF_STATIC_CONST_VAL_STRING(featval_3,"g");
DEF_STATIC_CONST_VAL_STRING(featval_4,"v");
DEF_STATIC_CONST_VAL_STRING(featval_5,"+");
DEF_STATIC_CONST_VAL_STRING(featval_6,"2");
DEF_STATIC_CONST_VAL_STRING(featval_7,"l");
DEF_STATIC_CONST_VAL_STRING(featval_8,"d");
DEF_STATIC_CONST_VAL_STRING(featval_9,"b");
DEF_STATIC_CONST_VAL_STRING(featval_10,"f");
DEF_STATIC_CONST_VAL_STRING(featval_11,"3");
DEF_STATIC_CONST_VAL_STRING(featval_12,"1");
DEF_STATIC_CONST_VAL_STRING(featval_13,"a");
DEF_STATIC_CONST_VAL_STRING(featval_14,"n");
DEF_STATIC_CONST_VAL_STRING(featval_15,"p");
DEF_STATIC_CONST_VAL_STRING(featval_16,"r");

static const cst_val * const cmu_grapheme_featvals[] = {
 (cst_val *)&featval_0,
 (cst_val *)&featval_1,
 (cst_val *)&featval_2,
 (cst_val *)&featval_3,
 (cst_val *)&featval_4,
 (cst_val *)&featval_5,
 (cst_val *)&featval_6,
 (cst_val *)&featval_7,
 (cst_val *)&featval_8,
 (cst_val *)&featval_9,
 (cst_val *)&featval_10,
 (cst_val *)&featval_11,
 (cst_val *)&featval_12,
 (cst_val *)&featval_13,
 (cst_val *)&featval_14,
 (cst_val *)&featval_15,
 (cst_val *)&featval_16,
 NULL };

const cst_phoneset cmu_grapheme_phoneset = {
  "cmu_grapheme",
  cmu_grapheme_featnames,
  cmu_grapheme_featvals,
  cmu_grapheme_phonenames,
  "pau",
  116,
  cmu_grapheme_fvtable,
  0  /* not freeable */
};
