#!/bin/sh
###########################################################################
##                                                                       ##
##                  Language Technologies Institute                      ##
##                     Carnegie Mellon University                        ##
##                      Copyright (c) 2014-2016                          ##
##                        All Rights Reserved.                           ##
##                                                                       ##
##  Permission is hereby granted, free of charge, to use and distribute  ##
##  this software and its documentation without restriction, including   ##
##  without limitation the rights to use, copy, modify, merge, publish,  ##
##  distribute, sublicense, and/or sell copies of this work, and to      ##
##  permit persons to whom this work is furnished to do so, subject to   ##
##  the following conditions:                                            ##
##   1. The code must retain the above copyright notice, this list of    ##
##      conditions and the following disclaimer.                         ##
##   2. Any modifications must be clearly marked as such.                ##
##   3. Original authors' names are not deleted.                         ##
##   4. The authors' names are not used to endorse or promote products   ##
##      derived from this software without specific prior written        ##
##      permission.                                                      ##
##                                                                       ##
##  CARNEGIE MELLON UNIVERSITY AND THE CONTRIBUTORS TO THIS WORK         ##
##  DISCLAIM ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING      ##
##  ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO EVENT   ##
##  SHALL CARNEGIE MELLON UNIVERSITY NOR THE CONTRIBUTORS BE LIABLE      ##
##  FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES    ##
##  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN   ##
##  AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,          ##
##  ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF       ##
##  THIS SOFTWARE.                                                       ##
##                                                                       ##
###########################################################################
##                                                                       ##
##  After a voice is built and dumped as a .flitevox file for            ##
##  distribution, add the feats to the file from ../etc/flite_feats      ##
##                                                                       ##
##  $FLITEDIR/tools/add_flite_feats X.flitevox ../etc/voice.feats        ##
##                                                                       ##
##  ../etc/voice.feats should look something like                        ##
##                                                                       ##
##  age 42                                                               ##
##  gender male                                                          ##
##  variant Scots                                                        ##
##                                                                       ##
##  If ../COPYING exists, the content is added as the feature copyright  ##
##                                                                       ##
###########################################################################

export LANG=C

awk '{if (NF > 1) print $0}' $2 | sed 's/"/\\"/g' |
awk '{printf("$FLITEDIR/bin/flitevox_info -set %s -val \"",$1);
     for (i=2; i<NF; i++)
            printf("%s ",$i);
     printf("%s\"\n",$NF);}' >do_feats

if [ -f ../COPYING ]
then
   cat ../COPYING | sed 's/"/\\"/g' |
   awk 'BEGIN {printf("$FLITEDIR/bin/flitevox_info -set copyright -val \"\n");}
        { printf("%s\n",$0); }
        END {printf("\"\n");}' >>do_feats
fi

cat do_feats | sed 's%info -set%info -voice '$1' -set%' >do_feats2

# Save the time on the flitevox file
touch -r $1 do_feats

sh ./do_feats2
$FLITEDIR/bin/flitevox_info -set build_date -val `tar cf - do_feats | tar tvf - | awk '{printf("%s_%s",$4,$5)}'` -voice $1

# Put the time back
touch -r do_feats $1
rm -f do_feats do_feats2

exit

