#!/bin/sh
###########################################################################
##                                                                       ##
##                  Language Technologies Institute                      ##
##                     Carnegie Mellon University                        ##
##                         Copyright (c) 2017                            ##
##                        All Rights Reserved.                           ##
##                                                                       ##
##  Permission is hereby granted, free of charge, to use and distribute  ##
##  this software and its documentation without restriction, including   ##
##  without limitation the rights to use, copy, modify, merge, publish,  ##
##  distribute, sublicense, and/or sell copies of this work, and to      ##
##  permit persons to whom this work is furnished to do so, subject to   ##
##  the following conditions:                                            ##
##   1. The code must retain the above copyright notice, this list of    ##
##      conditions and the following disclaimer.                         ##
##   2. Any modifications must be clearly marked as such.                ##
##   3. Original authors' names are not deleted.                         ##
##   4. The authors' names are not used to endorse or promote products   ##
##      derived from this software without specific prior written        ##
##      permission.                                                      ##
##                                                                       ##
##  CARNEGIE MELLON UNIVERSITY AND THE CONTRIBUTORS TO THIS WORK         ##
##  DISCLAIM ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING      ##
##  ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO EVENT   ##
##  SHALL CARNEGIE MELLON UNIVERSITY NOR THE CONTRIBUTORS BE LIABLE      ##
##  FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES    ##
##  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN   ##
##  AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,          ##
##  ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF       ##
##  THIS SOFTWARE.                                                       ##
##                                                                       ##
###########################################################################
##             Author:  Alan W Black (awb@cs.cmu.edu)                    ##
##               Date:  November 2017                                    ##
###########################################################################
##                                                                       ##
##  Download some .flitevox voices                                       ##
##                                                                       ##
###########################################################################

if [ ! -f include/flite.h ]
then
    echo "Not in the right directory."
    echo "You should be in the flite main src directory to run this script"
    echo "where ls -l include/flite.h is found"
    exit -1
fi

if [ ! -d voices ]
then
    mkdir voices
fi

if [ $# = 0 ]
then
    $0 us_voices
    exit 0
fi

FLITEVOICEDIR=http://tts.speech.cs.cmu.edu/festvox.org/flite/packed/flite-2.1/voices/
FLITEVOICEDIR=http://cmuflite.org/packed/flite-2.1/voices/
FLITEVOICEDIR=http://festvox.org/flite/packed/flite-2.1/voices/


if [ "$1" = "us_voices" ]
then
     cd voices
     wget $FLITEVOICEDIR/us_voices
     for i in `grep ".flitevox$" us_voices`
     do
         vname=`basename $i`
         rm -f $vname
         wget $FLITEVOICEDIR/$vname
     done
     rm -f us_voices
     exit 0
fi    

if [ "$1" = "indic_voices" ]
then
     cd voices
     wget $FLITEVOICEDIR/indic_voices
     for i in `grep ".flitevox$" indic_voices`
     do
         vname=`basename $i`
         rm -f $vname
         wget $FLITEVOICEDIR/$vname
     done
     rm -f indic_voices
     exit 0
fi    

if [ "$1" = "all_voices" ]
then
     $0 us_voices
     $0 indic_voices
     exit 0
fi    

exit



