#!/bin/sh
#####################################################-*-mode:shell-script-*-
##                                                                       ##
##                  Language Technologies Institute                      ##
##                     Carnegie Mellon University                        ##
##                         Copyright (c) 2013                            ##
##                        All Rights Reserved.                           ##
##                                                                       ##
##  Permission is hereby granted, free of charge, to use and distribute  ##
##  this software and its documentation without restriction, including   ##
##  without limitation the rights to use, copy, modify, merge, publish,  ##
##  distribute, sublicense, and/or sell copies of this work, and to      ##
##  permit persons to whom this work is furnished to do so, subject to   ##
##  the following conditions:                                            ##
##   1. The code must retain the above copyright notice, this list of    ##
##      conditions and the following disclaimer.                         ##
##   2. Any modifications must be clearly marked as such.                ##
##   3. Original authors' names are not deleted.                         ##
##   4. The authors' names are not used to endorse or promote products   ##
##      derived from this software without specific prior written        ##
##      permission.                                                      ##
##                                                                       ##
##  CARNEGIE MELLON UNIVERSITY AND THE CONTRIBUTORS TO THIS WORK         ##
##  DISCLAIM ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING      ##
##  ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO EVENT   ##
##  SHALL CARNEGIE MELLON UNIVERSITY NOR THE CONTRIBUTORS BE LIABLE      ##
##  FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES    ##
##  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN   ##
##  AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,          ##
##  ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF       ##
##  THIS SOFTWARE.                                                       ##
##                                                                       ##
###########################################################################
##                                                                       ##
##  Make empty lang and lex directories for a new language               ##
##                                                                       ##
###########################################################################

export LANG=C;

if [ $# = 0 ]
then
   echo ./tools/make_new_lang_lex LANGNAME
   echo Will make:
   echo    lang/cmu_${LANGNAME}_lex/cmu_${LANGNAME}_lex.h
   echo    lang/cmu_${LANGNAME}_lex/cmu_${LANGNAME}_lex.c
   echo    lang/cmu_${LANGNAME}_lang/cmu_${LANGNAME}_lang.h
   echo    lang/cmu_${LANGNAME}_lang/cmu_${LANGNAME}_lang.c
   echo You may want to use tools/build_lex to make a more complete
   echo set of files for lang/cmu_${LANGNAME}_lex/
   echo
   echo "Note this doesn't add anything to CVS, nor does it add the"
   echo "lang to the langlist (add them to config/default.lv) by hand"
fi

LANGNAME=$1

mkdir lang/cmu_${LANGNAME}_lex
cat tools/Makefile.lex |
sed 's/LANGNAME/'${LANGNAME}'/g' >lang/cmu_${LANGNAME}_lex/Makefile
cat tools/LANGNAME_lex.h |
sed 's/LANGNAME/'${LANGNAME}'/g' >lang/cmu_${LANGNAME}_lex/cmu_${LANGNAME}_lex.h
cat tools/LANGNAME_lex.c |
sed 's/LANGNAME/'${LANGNAME}'/g' >lang/cmu_${LANGNAME}_lex/cmu_${LANGNAME}_lex.c
echo made lang/cmu_${LANGNAME}_lex/ and skeleton files

mkdir lang/cmu_${LANGNAME}_lang
cat tools/Makefile.lang |
sed 's/LANGNAME/'${LANGNAME}'/g' >lang/cmu_${LANGNAME}_lang/Makefile
cat tools/LANGNAME_lang.h |
sed 's/LANGNAME/'${LANGNAME}'/g' >lang/cmu_${LANGNAME}_lang/cmu_${LANGNAME}_lang.h
cat tools/LANGNAME_lang.c |
sed 's/LANGNAME/'${LANGNAME}'/g' >lang/cmu_${LANGNAME}_lang/cmu_${LANGNAME}_lang.c
echo made lang/cmu_${LANGNAME}_lang/ and skeleton files


