#!/bin/sh
###########################################################################
##                                                                       ##
##                  Language Technologies Institute                      ##
##                     Carnegie Mellon University                        ##
##                         Copyright (c) 2016                            ##
##                        All Rights Reserved.                           ##
##                                                                       ##
##  Permission is hereby granted, free of charge, to use and distribute  ##
##  this software and its documentation without restriction, including   ##
##  without limitation the rights to use, copy, modify, merge, publish,  ##
##  distribute, sublicense, and/or sell copies of this work, and to      ##
##  permit persons to whom this work is furnished to do so, subject to   ##
##  the following conditions:                                            ##
##   1. The code must retain the above copyright notice, this list of    ##
##      conditions and the following disclaimer.                         ##
##   2. Any modifications must be clearly marked as such.                ##
##   3. Original authors' names are not deleted.                         ##
##   4. The authors' names are not used to endorse or promote products   ##
##      derived from this software without specific prior written        ##
##      permission.                                                      ##
##                                                                       ##
##  CARNEGIE MELLON UNIVERSITY AND THE CONTRIBUTORS TO THIS WORK         ##
##  DISCLAIM ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING      ##
##  ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO EVENT   ##
##  SHALL CARNEGIE MELLON UNIVERSITY NOR THE CONTRIBUTORS BE LIABLE      ##
##  FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES    ##
##  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN   ##
##  AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,          ##
##  ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF       ##
##  THIS SOFTWARE.                                                       ##
##                                                                       ##
###########################################################################
##                                                                       ##
##  After a voice is built and dumped as a .flitevox file for            ##
##  run tests to ensure the fornt end is working properly                ##
##                                                                       ##
##  $FLITEDIR/tools/run_flitecheck VOICE.flitevox                        ##
##                                                                       ##
##  It works out the right .flitechecks file to use from the voice name  ##
##  or it may be specified as an optional argument                       ##
##                                                                       ##
###########################################################################

export LANG=C

if [ $# = 2 ]
then
    FLITECHECK_FILE=$2
else
    fname=`basename $1`
    llang=`echo $fname | sed 's/_/ /g' | awk '{if ($2 == "indic") printf("%s_%s",$2,$3)
                                           else print $2}'`
    FLITECHECK_FILE=$FLITEDIR/testsuite/$llang.flitecheck
fi

FLITE_VOICE=$1

$FLITEDIR/bin/flitechecks $FLITE_VOICE $FLITECHECK_FILE

exit

